FastFiz: Pool::NineBallState Class Reference
Pool::NineBallState Class Reference
Implementation of the rules of Nine-Ball.
#include <Rules.h>
Public Member Functions
NineBallState (double timeleft=0.0, double timeleft_opp=0.0)
NineBallState (string gameString)
GameType gameType () const
Returns the type of game (GT_NINEBALL)
NineBallState (istream &is)
virtual void toStream (ostream &out) const
Exports the GameState to a stream.
virtual GameState * clone ()
Allocate a new copy of this GameState.
virtual bool shotRequired () const
Determines if the agent is required to provide a valid shot.
Public Member Functions inherited from Pool::GameState
GameState (double timeleft=0.0, double timeleft_opp=0.0)
Create new game state.
GameState (string gameString)
Parse common part of GameState from string.
virtual bool isTerminal () const
Determines if the GameState is in a terminal state (i.e.
virtual bool positionRequired () const
Determines if the agent must provide a valid position for the cue ball.
virtual bool decisionAllowed () const
Determines if the agent is allowed to make a decision.
virtual string toString ()
Serializes the GameState as a string.
virtual const bool isOpenTable () const
Returns true if solids/stripes have not been determined yet.
virtual const TurnType getTurnType () const
virtual const bool playingSolids () const
Returns true if current player should shoot solids.
virtual const bool curPlayerStarted () const
Returns true if the current player had the inital break.
virtual const double timeLeft () const
Returns the amount of time left (in seconds) for the current player.
virtual const double timeLeftOpp () const
Returns the amount of time left (in seconds) for the other player.
virtual const TableState & tableState () const
Allows caller read-only access to the internal table state.
virtual ShotResult executeShot (const GameShot &shot, Shot **shotObj=NULL)
Calls the rules to check the shot values, executes the shot using the physics library, and then evalues the resulting GameState.
Protected Member Functions
virtual void importFromStream (istream &sourceStream)
Read common information from an input stream.
virtual bool isLegalTurnType () const
Returns true if the current turnType is defined for the current game.
virtual PreProcessCode preProcess (const GameShot &shot)
Pre-evaluate shot parameters for the current game state.
virtual void processShot (const vector< Event * > &eventList, const GameShot &gameShot)
Called after shot execution to process an event list and adjust game state.
virtual void rack ()
Update TableState to the racked state, does NOT update other params.
virtual void switchSides ()
Utility function to switch the active player.
Protected Attributes
int _fouls
int _opp_fouls
Protected Attributes inherited from Pool::GameState
TableState _tableState
TurnType _turnType
double _timeLeft
double _timeLeftOpp
bool _curPlayerStarted
bool _switchedSides
Friends
ostream & operator<< (ostream &os, const NineBallState &obj)
istream & operator>> (istream &is, NineBallState &obj)
Additional Inherited Members
Static Public Member Functions inherited from Pool::GameState
static GameState * Factory (istream &sourceStream)
Generate a new GameState object by reading information from an input stream.
static GameState * Factory (string sourceString)
Generate a new GameState object by reading information from an input string.
static GameState * RackedState (GameType gameType)
Returns a newly allocated racked (initial) state of a game by game type.
Protected Types inherited from Pool::GameState
enum PreProcessCode { PPC_BADPARAMS =0, PPC_G_NOEXECUTE, PPC_G_NORMAL, PPC_G_PLACECUE }
Possible results of pre-evaluation of shot parameters for current game state.
Detailed Description
Implementation of the rules of Nine-Ball.
Definition at line 394 of file Rules.h.
Constructor & Destructor Documentation
Pool::NineBallState::NineBallState (double timeleft = 0.0, double timeleft_opp = 0.0) inline explicit
Definition at line 399 of file Rules.h.
References Pool::operator<<(), Pool::operator>>(), and Pool::rack().
Pool::NineBallState::NineBallState (string gameString) inline
Definition at line 411 of file Rules.h.
Pool::NineBallState::NineBallState (istream & is) inline
Definition at line 424 of file Rules.h.
Member Function Documentation
GameState * NineBallState::clone () virtual
Allocate a new copy of this GameState.
Implements Pool::GameState.
Definition at line 750 of file Rules.cpp.
GameType Pool::NineBallState::gameType () const inline virtual
Returns the type of game (GT_NINEBALL)
Implements Pool::GameState.
Definition at line 421 of file Rules.h.
References Pool::GT_NINEBALL.
void NineBallState::importFromStream (istream & sourceStream) protected virtual
Read common information from an input stream.
Reimplemented from Pool::GameState.
Definition at line 559 of file Rules.cpp.
References importFromStream(), and Pool::operator>>().
Referenced by importFromStream().
virtual bool Pool::NineBallState::isLegalTurnType () const inline protected virtual
Returns true if the current turnType is defined for the current game.
Reimplemented from Pool::GameState.
Definition at line 445 of file Rules.h.
References Pool::GameState::isLegalTurnType(), Pool::rack(), Pool::TT_BEHIND_LINE, Pool::TT_NINEBALL_FIRST_SHOT, and Pool::TT_NINEBALL_PUSH_OUT.
GameState::PreProcessCode NineBallState::preProcess (const GameShot & shot) protected virtual
Pre-evaluate shot parameters for the current game state.
Implements Pool::GameState.
Definition at line 582 of file Rules.cpp.
References Pool::GameShot::cue_y, Pool::DEC_CONCEDE, Pool::DEC_KEEP_SHOOTING, Pool::DEC_NINEBALL_PUSH_OUT, Pool::DEC_NO_DECISION, Pool::GameShot::decision, Pool::TT_BALL_IN_HAND, Pool::TT_BREAK, Pool::TT_NINEBALL_FIRST_SHOT, Pool::TT_NINEBALL_PUSH_OUT, Pool::TT_NORMAL, and Pool::TT_WIN.
void NineBallState::processShot (const vector< Event * > & eventList, const GameShot & gameShot) protected virtual
Called after shot execution to process an event list and adjust game state.
Implements Pool::GameState.
Definition at line 633 of file Rules.cpp.
References Pool::DEC_NINEBALL_PUSH_OUT, Pool::GameShot::decision, Pool::TT_BALL_IN_HAND, Pool::TT_BREAK, Pool::TT_NINEBALL_FIRST_SHOT, Pool::TT_NINEBALL_PUSH_OUT, Pool::TT_NORMAL, and Pool::TT_WIN.
void NineBallState::rack () protected virtual
Update TableState to the racked state, does NOT update other params.
Implements Pool::GameState.
Definition at line 717 of file Rules.cpp.
References Pool::Table::getFootSpot(), Pool::Table::getHeadString(), Pool::Table::getWidth(), Pool::Point::x, and Pool::Point::y.
virtual bool Pool::NineBallState::shotRequired () const inline virtual
Determines if the agent is required to provide a valid shot.
Reimplemented from Pool::GameState.
Definition at line 435 of file Rules.h.
References Pool::GameState::shotRequired(), and Pool::TT_NINEBALL_PUSH_OUT.
void NineBallState::switchSides () protected virtual
Utility function to switch the active player.
Reimplemented from Pool::GameState.
Definition at line 574 of file Rules.cpp.
void NineBallState::toStream (ostream & out) const virtual
Exports the GameState to a stream.
Reimplemented from Pool::GameState.
Definition at line 743 of file Rules.cpp.
Friends And Related Function Documentation
ostream& operator<< (ostream & os, const NineBallState & obj) friend
istream& operator>> (istream & is, NineBallState & obj) friend
Member Data Documentation
int Pool::NineBallState::_fouls protected
Definition at line 469 of file Rules.h.
int Pool::NineBallState::_opp_fouls protected
Definition at line 469 of file Rules.h.
The documentation for this class was generated from the following files:
Rules.h
Rules.cpp