FastFiz: Pool::RailCollisionEvent Class Reference
Pool::RailCollisionEvent Class Reference
An event involving a ball colliding with a rail.
#include <FastFiz.h>
Public Member Functions
RailCollisionEvent (double time, Ball::Type b, Table::BoundaryId rail)
virtual Type getType () const
Returns the type of the event.
virtual string getTypeString () const
Returns the type of the event as a string.
Table::BoundaryId getRail () const
Returns the ID of the rail collided with.
Public Member Functions inherited from Pool::Event
Event (double time, Ball::Type b)
Create a new base event.
double getTime () const
Returns the event's simulation time index.
Ball::Type getBall1 () const
Returns the id of first (possibly only) ball involved in the event.
Ball & getBall1Data ()
Returns the physical information (location, velocity,spin) of the first (possibly only) ball involved in the event.
bool operator< (const Event &other) const
Sorts Events by time.
string toString () const
Returns a human-readble string representation of the event.
virtual Ball::Type getBall2 () const
Returns the id of the second ball involved in the event, if applicable.
virtual Ball & getBall2Data ()
Returns the physical information (location, velocity,spin) of the second ball involved in the event.
virtual bool relatedTo (const Event &other) const
Returns true if this event and the other event affect a shared ball.
virtual bool involvesBall (Ball::Type b) const
Returns true if this event affects specified ball.
virtual ~Event ()
Destructor.
void handle (TableState &ts, bool VERBOSE=false)
Used within physics code to apply event to a table state, modifying ball states, positions, and properties Also updates ball information within event.
Protected Member Functions
virtual void doHandle (TableState &ts, bool VERBOSE) const
virtual ostream & dump (ostream &out) const
Protected Member Functions inherited from Pool::Event
virtual void copyBalls (TableState &ts)
Protected Attributes
Table::BoundaryId _rail
Protected Attributes inherited from Pool::Event
double _time
Ball::Type _ball1
Ball * _ball1Data
Additional Inherited Members
Public Types inherited from Pool::Event
enum Type {
NO_EVENT, STATE_CHANGE, BALL_COLLISION, RAIL_COLLISION,
POCKETED, CUE_STRIKE, MISCUE, UNKNOWN_EVENT
}
Indicates the type of event.
Static Public Member Functions inherited from Pool::Event
static bool eventCmp (const Event *event1, const Event *event2)
Event comparison function, calls operator<.
Detailed Description
An event involving a ball colliding with a rail.
Definition at line 837 of file FastFiz.h.
Constructor & Destructor Documentation
Pool::RailCollisionEvent::RailCollisionEvent (double time, Ball::Type b, Table::BoundaryId rail) inline
Definition at line 839 of file FastFiz.h.
Member Function Documentation
void Pool::RailCollisionEvent::doHandle (TableState & ts, bool VERBOSE) const protected virtual
Implements Pool::Event.
Definition at line 807 of file FastFiz.cpp.
References Pool::Table::boundaryName(), Pool::TableState::getBall(), Pool::Ball::getIDString(), Pool::Ball::getSpin(), Pool::Ball::getVelocity(), Pool::Table::N_RAIL, Pool::Table::S_RAIL, Pool::Ball::setSpin(), Pool::Ball::setVelocity(), Pool::Ball::updateState(), Pool::Vector::x, and Pool::Vector::y.
ostream & Pool::RailCollisionEvent::dump (ostream & out) const protected virtual
Reimplemented from Pool::Event.
Definition at line 941 of file FastFiz.cpp.
References Pool::Table::boundaryName(), and Pool::Event::dump().
Table::BoundaryId Pool::RailCollisionEvent::getRail () const inline
Returns the ID of the rail collided with.
Definition at line 846 of file FastFiz.h.
virtual Type Pool::RailCollisionEvent::getType () const inline virtual
Returns the type of the event.
Reimplemented from Pool::Event.
Definition at line 842 of file FastFiz.h.
virtual string Pool::RailCollisionEvent::getTypeString () const inline virtual
Returns the type of the event as a string.
Reimplemented from Pool::Event.
Definition at line 843 of file FastFiz.h.
Member Data Documentation
Table::BoundaryId Pool::RailCollisionEvent::_rail protected
Definition at line 848 of file FastFiz.h.
The documentation for this class was generated from the following files:
FastFiz.h
FastFiz.cpp