FastFiz: Pool::Noise Class Reference
Pool::Noise Class Reference abstract
Base Noise class for implementing a generic type of noise.
#include <Noise.h>
Public Member Functions
virtual void toStream (ostream &out) const
virtual string toString ()
virtual NoiseType noiseType () const =0
Return the type of noise used.
virtual void applyNoise (ShotParams &sp) const =0
Apply the noise to the given shot parameters.
Static Public Member Functions
static Noise * Factory (istream &sourceStream)
Factory Function – read noise info from a stream.
static Noise * Factory (string sourceString)
Factory Function – read noise info from a string.
Protected Member Functions
virtual void importFromStream (istream &sourceStream)
Friends
ostream & operator<< (ostream &os, const Noise &obj)
Detailed Description
Base Noise class for implementing a generic type of noise.
Definition at line 31 of file Noise.h.
Member Function Documentation
virtual void Pool::Noise::applyNoise (ShotParams & sp) const pure virtual
Apply the noise to the given shot parameters.
Parameters
sp Shot parameters – will be changed.
Implemented in Pool::GaussianNoise, and Pool::NoNoise.
Pool::Noise * Pool::Noise::Factory (istream & sourceStream) static
Factory Function – read noise info from a stream.
Definition at line 27 of file Noise.cpp.
References Pool::NT_GAUSSIAN, and Pool::NT_NONE.
static Noise* Pool::Noise::Factory (string sourceString) inline static
Factory Function – read noise info from a string.
Definition at line 38 of file Noise.h.
References Pool::operator<<().
virtual void Pool::Noise::importFromStream (istream & sourceStream) inline protected virtual
Reimplemented in Pool::GaussianNoise.
Definition at line 67 of file Noise.h.
References Pool::operator<<().
virtual NoiseType Pool::Noise::noiseType () const pure virtual
Return the type of noise used.
Implemented in Pool::GaussianNoise, and Pool::NoNoise.
void Pool::Noise::toStream (ostream & out) const virtual
Reimplemented in Pool::GaussianNoise.
Definition at line 63 of file Noise.cpp.
Referenced by Pool::operator<<(), and Pool::LogWriter::write().
string Pool::Noise::toString () virtual
Definition at line 56 of file Noise.cpp.
Friends And Related Function Documentation
ostream& operator<< (ostream & os, const Noise & obj) friend
The documentation for this class was generated from the following files:
Noise.h
Noise.cpp