FastFiz: Pool::LogWriter Class Reference
Pool::LogWriter Class Reference
Output game/table states and shots to a stream in a text-based format supported by web-based game viewer.
#include <LogFile.h>
Public Member Functions
LogWriter (ostream &os, const GameType gameType=GT_NONE, const Noise *const noise=0, const string agentName="Default Agent", const string opponentName="")
Start a new log.
LogWriter (const char *const filename, const GameType gameType=GT_NONE, const Noise *const noise=0, const string agentName="Default Agent", const string opponentName="")
Start a new log file (conveinent version of constructor for files).
void setNoise (const Noise *const noise)
Set Noise type for future shots.
void setAgents (const string agentName, const string opponentName="")
Set agent names.
void swapAgents ()
Make opponent agent active (for future shots) and set active agent as opponent.
void write (const GameState &gs)
Add Entry to log file with given game state.
void write (const GameShot &gs, double duration=0.0)
Add Entry to log file with given shot.
void write (const GameShot &gs, const ShotParams &noiselessParams, double duration=0.0)
Add Entry to log file with given shot.
void write (const TableState &ts)
Add a brief state entry to log file.
void write (const ShotParams &sp)
Add a brief shot entry to log file.
void comment (const string text)
Adds a comment to the log file.
ShotResult LogAndExecute (GameState &gst, const GameShot &gsh, const ShotParams &noiselessParams)
Execute specified shot and if physically possible, write previous state and the actual shot to file.
ShotResult LogAndExecute (GameState &gst, GameShot &gsh)
Add random noise, then execute specified shot and if physically possible, write previous state and the actual shot to file.
~LogWriter ()
Protected Member Functions
void writeHeader (const GameType gt)
Utility function to write the GTYPE header to the stream.
void writeShotParams (const ShotParams &sp)
Utility function to serialize a,b,theta,phi,v to the stream.
Protected Attributes
string _agentName
string _opponentName
const Noise * _noise
ofstream * _ofs
ostream & _os
Detailed Description
Output game/table states and shots to a stream in a text-based format supported by web-based game viewer.
This class allows for testing shots offline without writing a complete AI. The resulting log file can then be used to visualize the results of the shots.
Log files can also be used as a convenient way to store shots or table states for later use.
Definition at line 31 of file LogFile.h.
Constructor & Destructor Documentation
Pool::LogWriter::LogWriter (ostream & os, const GameType gameType = GT_NONE, const Noise *const noise = 0, const string agentName = "Default Agent", const string opponentName = "") inline
Start a new log.
Parameters
os Output stream to write log.
gameType Type of game being played (e.g. GT_EIGHTBALL).
noise Noise object being used. Noise info will be written to log.
agentName Name of agent executing the shots (usually ai.getName()).
opponentName Name of opponent to be written to log.
Definition at line 42 of file LogFile.h.
Pool::LogWriter::LogWriter (const char *const filename, const GameType gameType = GT_NONE, const Noise *const noise = 0, const string agentName = "Default Agent", const string opponentName = "") inline
Start a new log file (conveinent version of constructor for files).
Parameters
filename Name of file to write.
gameType Type of game being played (e.g. GT_EIGHTBALL).
noise Noise object being used. Noise info will be written to log.
agentName Name of agent executing the shots (usually ai.getName()).
opponentName Name of opponent to be written to log.
Definition at line 56 of file LogFile.h.
Pool::LogWriter::~LogWriter () inline
Definition at line 133 of file LogFile.h.
Member Function Documentation
void LogWriter::comment (const string text)
Adds a comment to the log file.
Comment will be displayed in game viewer with next shot.
Definition at line 52 of file LogFile.cpp.
Referenced by main().
ShotResult LogWriter::LogAndExecute (GameState & gst, const GameShot & gsh, const ShotParams & noiselessParams)
Execute specified shot and if physically possible, write previous state and the actual shot to file.
Note that that given game state will be modified.
Parameters
gst Game State before the shot, will be modified to reflect the state after the shot.
gsh Shot to execute. Noise will not be added.
noiselessParams Shot parameters before noise was applied.
Definition at line 57 of file LogFile.cpp.
References Pool::GameState::clone(), Pool::GameState::executeShot(), Pool::Shot::getDuration(), Pool::SR_OK, and Pool::SR_OK_LOST_TURN.
ShotResult LogWriter::LogAndExecute (GameState & gst, GameShot & gsh)
Add random noise, then execute specified shot and if physically possible, write previous state and the actual shot to file.
Note that that given game state and shot will be modified.
Parameters
gst Game State before the shot, will be modified to reflect the state after the shot.
gsh Shot to execute. Noise will be added, and gsh will be modified to reflect parameters with noise added.
Definition at line 71 of file LogFile.cpp.
References Pool::GameShot::params.
void Pool::LogWriter::setAgents (const string agentName, const string opponentName = "") inline
Set agent names.
Parameters
agentName Name of agent executing future shots.
opponentName Name of the other agent.
Definition at line 72 of file LogFile.h.
void Pool::LogWriter::setNoise (const Noise *const noise) inline
Set Noise type for future shots.
Useful when noise is variable.
Definition at line 65 of file LogFile.h.
void Pool::LogWriter::swapAgents () inline
Make opponent agent active (for future shots) and set active agent as opponent.
Definition at line 77 of file LogFile.h.
void LogWriter::write (const GameState & gs)
Add Entry to log file with given game state.
Definition at line 12 of file LogFile.cpp.
Referenced by main().
void Pool::LogWriter::write (const GameShot & gs, double duration = 0.0) inline
Add Entry to log file with given shot.
No noise will be added, so noiseless parameters will equal noisy ones. Shot will not be executed, but noise information and agent names will be written.
Definition at line 88 of file LogFile.h.
References Pool::GameShot::params.
void LogWriter::write (const GameShot & gs, const ShotParams & noiselessParams, double duration = 0.0)
Add Entry to log file with given shot.
No noise will be added. Shot will not be executed, but noise information and agent names will be written.
Parameters
gs Shot to write to file (actual shot executed).
noiselessParams Shot parameters given by AI before noise was added.
duration Simulation time in seconds for shot, or zero to avoid including simulation time.
Definition at line 21 of file LogFile.cpp.
References Pool::GameShot::ball, Pool::GameShot::cue_x, Pool::GameShot::cue_y, Pool::GameShot::decision, Pool::GameShot::params, Pool::GameShot::pocket, Pool::GameShot::timeSpent, and Pool::Noise::toStream().
void LogWriter::write (const TableState & ts)
Add a brief state entry to log file.
Entry will only include location of balls of the table and will not include any game-related information. Mostly useful for physics experimentation and debugging.
Definition at line 38 of file LogFile.cpp.
References Pool::TableState::toStream().
void LogWriter::write (const ShotParams & sp)
Add a brief shot entry to log file.
Entry will only include physical shot parameters. Cue ball must already be positioned on the table. Mostly useful for physics experimentation and debugging.
Definition at line 45 of file LogFile.cpp.
void LogWriter::writeHeader (const GameType gt) protected
Utility function to write the GTYPE header to the stream.
Definition at line 80 of file LogFile.cpp.
void LogWriter::writeShotParams (const ShotParams & sp) protected
Utility function to serialize a,b,theta,phi,v to the stream.
Definition at line 17 of file LogFile.cpp.
References Pool::ShotParams::a, Pool::ShotParams::b, Pool::ShotParams::phi, Pool::ShotParams::theta, and Pool::ShotParams::v.
Member Data Documentation
string Pool::LogWriter::_agentName protected
Definition at line 145 of file LogFile.h.
const Noise* Pool::LogWriter::_noise protected
Definition at line 146 of file LogFile.h.
ofstream* Pool::LogWriter::_ofs protected
Definition at line 147 of file LogFile.h.
string Pool::LogWriter::_opponentName protected
Definition at line 145 of file LogFile.h.
ostream& Pool::LogWriter::_os protected
Definition at line 148 of file LogFile.h.
The documentation for this class was generated from the following files:
LogFile.h
LogFile.cpp