FastFiz: Pool::Ball Class Reference
Pool::Ball Class Reference
This class represents the state and position of a single pool ball.
#include <FastFiz.h>
Public Types
enum State {
NOTINPLAY, STATIONARY, SPINNING, SLIDING,
ROLLING, POCKETED_SW, POCKETED_W, POCKETED_NW,
POCKETED_NE, POCKETED_E, POCKETED_SE, SLIDING_SPINNING,
ROLLING_SPINNING, UNKNOWN_STATE
}
The present physical state of the ball.
enum Type {
CUE, ONE, TWO, THREE,
FOUR, FIVE, SIX, SEVEN,
EIGHT, NINE, TEN, ELEVEN,
TWELVE, THIRTEEN, FOURTEEN, FIFTEEN,
UNKNOWN_ID
}
The type (number) of the ball.
Public Member Functions
Ball ()
Create a new ball.
Ball (Type _type)
Create a new ball with specified number.
Ball (Type _type, State _state)
Create a new ball with specified number and state.
Ball (Type _type, State _state, Point _r)
Create a new ball with specified number, state, and position.
Ball (Type _type, State _state, double x, double y)
Create a new ball with specified number, state, and position.
Ball (const Ball &rhs)
Copy constructor.
const Ball & operator= (const Ball &rhs)
Assignment operator.
const double getRadius () const
Returns the radius of the ball in meters.
const Type getID () const
Returns the ID (number) of the ball.
string getIDString () const
Returns the name of the ball (CUE, ONE, etc.) as a string.
const State getState () const
Returns the physical state of the ball.
string getStateString () const
Returns the physical state of the ball as a string.
const Point & getPos () const
Returns the x,y position of the ball.
const Vector & getVelocity () const
Returns the x,y,z velocity of the ball.
const Vector & getSpin () const
Returns the x,y,z spin of the ball.
void setID (Type t)
Set the number of the ball.
void setPos (Point pos)
Set the position of the ball.
void setVelocity (Vector vel)
Set the velocity of the ball.
void setSpin (Vector spin)
Set the spin of the ball.
void setState (State s)
Set the physical state of the ball.
bool isInPlay () const
Returns true iff the ball is on the table.
bool isPocketed () const
Returns true iff the ball is in a pocket.
bool overlaps (const Ball &other, double epsilon=Utils::EPSILON) const
Returns true if the ball occupies the same space as the other ball.
void moveAway (Ball &other, double epsilon)
double dist (const Ball &other) const
Returns the distance between the centers of this ball and the other ball.
void addNoise (double dither)
Add small gaussian noise to ball's position based on dither parameter passed.
void updateState (bool VERBOSE=false)
Update balls physical state based on position, velocity, and spin.
void toStream (ostream &out) const
Print a machine-readable representation of the ball's type, radius and position.
void fromStream (istream &in)
Read a machine-readable representation of the ball's type, radius and position.
string toString () const
Returns a string including a machine-readable representation of the ball's type, radius and position.
void fromString (const string &s)
Read a machine-readable representation of the ball's type, radius and position from string.
Static Public Attributes
static const double MU_BALL_BALL = 0.01
coefficient of ball-ball friction
static const double MU_CUETIP_BALL = 0.7
coefficient of cue tip-ball friction
static const double BALL_COEFF_REST_POS = 2.0
coefficient of restitution for balls
static const double BALL_COEFF_REST_NEG = 0.0
coefficient of restitution for balls
static const double BALL_MASS = 163.01
5.57 oz.
static const double BALL_RADIUS = 0.028575
2.25" ball radius [m]
Detailed Description
This class represents the state and position of a single pool ball.
It is mostly used internally for execution of the physics, and as part of a TableState object.
Definition at line 355 of file FastFiz.h.
Member Enumeration Documentation
enum Pool::Ball::State
The present physical state of the ball.
Enumerator
NOTINPLAY
not on the table
STATIONARY
in play but not moving
SPINNING
not moving translationally, but spinning in place about the vertical axis
SLIDING
sliding across the surface of the table, not necessarily in a straight trajectory
ROLLING
rolling across the surface of the table, necessarily in a straight trajectory
POCKETED_SW
pocketed in the SW pocket
POCKETED_W
pocketed in the W pocket
POCKETED_NW
pocketed in the NW pocket
POCKETED_NE
pocketed in the NE pocket
POCKETED_E
pocketed in the E pocket
POCKETED_SE
pocketed in the SE pocket
SLIDING_SPINNING
Transition between SLIDING and SPINNING.
ROLLING_SPINNING
Transition between ROLLING and SPINNING.
UNKNOWN_STATE
in an unknown state
Definition at line 368 of file FastFiz.h.
enum Pool::Ball::Type
The type (number) of the ball.
Enumerator
CUE
ONE
TWO
THREE
FOUR
FIVE
SIX
SEVEN
EIGHT
NINE
TEN
ELEVEN
TWELVE
THIRTEEN
FOURTEEN
FIFTEEN
UNKNOWN_ID
Definition at line 384 of file FastFiz.h.
Constructor & Destructor Documentation
Pool::Ball::Ball () inline
Create a new ball.
Definition at line 389 of file FastFiz.h.
Pool::Ball::Ball (Type _type) inline
Create a new ball with specified number.
Definition at line 392 of file FastFiz.h.
Pool::Ball::Ball (Type _type, State _state) inline
Create a new ball with specified number and state.
Definition at line 395 of file FastFiz.h.
Pool::Ball::Ball (Type _type, State _state, Point _r) inline
Create a new ball with specified number, state, and position.
Definition at line 397 of file FastFiz.h.
Pool::Ball::Ball (Type _type, State _state, double x, double y) inline
Create a new ball with specified number, state, and position.
Definition at line 399 of file FastFiz.h.
Pool::Ball::Ball (const Ball & rhs) inline
Copy constructor.
Definition at line 403 of file FastFiz.h.
Member Function Documentation
void Pool::Ball::addNoise (double dither)
Add small gaussian noise to ball's position based on dither parameter passed.
This method is used for racking and spotting noise, and has nothing to do with shot execution noise.
Definition at line 2531 of file FastFiz.cpp.
References Pool::Utils::rng().
double Pool::Ball::dist (const Ball & other) const inline
Returns the distance between the centers of this ball and the other ball.
Note that a positive distance does not indicate no overlap. No overlap is ensured if the distance is greater than the sum of the radiuses of the balls.
Definition at line 341 of file FastFiz.cpp.
References Pool::Point::x, and Pool::Point::y.
Referenced by Pool::TableState::isValidBallPlacement().
void Pool::Ball::fromStream (istream & in)
Read a machine-readable representation of the ball's type, radius and position.
Should be used on data written by toStream()/toString().
Definition at line 397 of file FastFiz.cpp.
Referenced by Pool::TableState::fromStream().
void Pool::Ball::fromString (const string & s)
Read a machine-readable representation of the ball's type, radius and position from string.
Should be used on data created by toString()/toStream().
Definition at line 413 of file FastFiz.cpp.
const Type Pool::Ball::getID () const inline
Returns the ID (number) of the ball.
Definition at line 412 of file FastFiz.h.
Referenced by Pool::Shot::getDuration(), and Pool::TableState::setBall().
string Pool::Ball::getIDString () const
Returns the name of the ball (CUE, ONE, etc.) as a string.
Definition at line 287 of file FastFiz.cpp.
Referenced by Pool::BallCollisionEvent::doHandle(), Pool::RailCollisionEvent::doHandle(), Pool::PocketedEvent::doHandle(), Pool::Event::dump(), Pool::BallCollisionEvent::dump(), Pool::Shot::getDuration(), and Pool::operator<<().
const Point& Pool::Ball::getPos () const inline
Returns the x,y position of the ball.
Definition at line 420 of file FastFiz.h.
Referenced by Pool::BallCollisionEvent::doHandle(), Pool::Shot::getDuration(), Pool::TableState::isValidBallPlacement(), Pool::operator<<(), Pool::EightBallState::processShot(), and Pool::TableState::setBall().
const double Pool::Ball::getRadius () const inline
Returns the radius of the ball in meters.
Definition at line 410 of file FastFiz.h.
Referenced by Pool::BallCollisionEvent::doHandle(), Pool::CueStrikeEvent::doHandle(), and Pool::Shot::getDuration().
const Vector& Pool::Ball::getSpin () const inline
Returns the x,y,z spin of the ball.
Definition at line 424 of file FastFiz.h.
Referenced by Pool::BallCollisionEvent::doHandle(), Pool::RailCollisionEvent::doHandle(), Pool::CueStrikeEvent::doHandle(), Pool::Shot::getDuration(), and Pool::operator<<().
const State Pool::Ball::getState () const inline
Returns the physical state of the ball.
Definition at line 416 of file FastFiz.h.
Referenced by Pool::BallCollisionEvent::doHandle(), Pool::Shot::getDuration(), and Pool::TableState::setBall().
string Pool::Ball::getStateString () const
Returns the physical state of the ball as a string.
Definition at line 312 of file FastFiz.cpp.
Referenced by Pool::operator<<(), and updateState().
const Vector& Pool::Ball::getVelocity () const inline
Returns the x,y,z velocity of the ball.
Definition at line 422 of file FastFiz.h.
Referenced by Pool::BallCollisionEvent::doHandle(), Pool::RailCollisionEvent::doHandle(), Pool::CueStrikeEvent::doHandle(), Pool::Shot::getDuration(), and Pool::operator<<().
bool Pool::Ball::isInPlay () const inline
Returns true iff the ball is on the table.
Definition at line 437 of file FastFiz.h.
Referenced by Pool::TableState::isValidBallPlacement().
bool Pool::Ball::isPocketed () const inline
Returns true iff the ball is in a pocket.
Definition at line 439 of file FastFiz.h.
References Pool::operator<<().
void Pool::Ball::moveAway (Ball & other, double epsilon)
Definition at line 2750 of file FastFiz.cpp.
const Ball & Pool::Ball::operator= (const Ball & rhs)
Assignment operator.
Definition at line 275 of file FastFiz.cpp.
bool Pool::Ball::overlaps (const Ball & other, double epsilon = Utils::EPSILON) const inline
Returns true if the ball occupies the same space as the other ball.
Definition at line 334 of file FastFiz.cpp.
References Pool::Point::x, and Pool::Point::y.
Referenced by Pool::TableState::isValidBallPlacement().
void Pool::Ball::setID (Type t) inline
Set the number of the ball.
Definition at line 427 of file FastFiz.h.
void Pool::Ball::setPos (Point pos) inline
Set the position of the ball.
Definition at line 429 of file FastFiz.h.
Referenced by Pool::Shot::getDuration().
void Pool::Ball::setSpin (Vector spin) inline
Set the spin of the ball.
Definition at line 433 of file FastFiz.h.
Referenced by Pool::BallCollisionEvent::doHandle(), Pool::RailCollisionEvent::doHandle(), Pool::PocketedEvent::doHandle(), Pool::CueStrikeEvent::doHandle(), and Pool::Shot::getDuration().
void Pool::Ball::setState (State s) inline
Set the physical state of the ball.
Definition at line 435 of file FastFiz.h.
Referenced by Pool::PocketedEvent::doHandle(), and updateState().
void Pool::Ball::setVelocity (Vector vel) inline
Set the velocity of the ball.
Definition at line 431 of file FastFiz.h.
Referenced by Pool::BallCollisionEvent::doHandle(), Pool::RailCollisionEvent::doHandle(), Pool::PocketedEvent::doHandle(), Pool::CueStrikeEvent::doHandle(), and Pool::Shot::getDuration().
void Pool::Ball::toStream (ostream & out) const
Print a machine-readable representation of the ball's type, radius and position.
Only writes location information, not velocity and spin.
Definition at line 390 of file FastFiz.cpp.
string Pool::Ball::toString () const
Returns a string including a machine-readable representation of the ball's type, radius and position.
Only outputs location information, not velocity and spin.
Definition at line 407 of file FastFiz.cpp.
void Pool::Ball::updateState (bool VERBOSE = false)
Update balls physical state based on position, velocity, and spin.
Used internally for physics calculations.
Definition at line 345 of file FastFiz.cpp.
References Pool::Vector::cross(), getStateString(), Pool::Vector::mag(), setState(), Pool::Utils::vzero(), Pool::Vector::x, and Pool::Vector::y.
Referenced by Pool::StateChangeEvent::doHandle(), Pool::BallCollisionEvent::doHandle(), Pool::RailCollisionEvent::doHandle(), Pool::CueStrikeEvent::doHandle(), and Pool::Shot::getDuration().
Member Data Documentation
const double Pool::Ball::BALL_COEFF_REST_NEG = 0.0 static
coefficient of restitution for balls
Definition at line 362 of file FastFiz.h.
const double Pool::Ball::BALL_COEFF_REST_POS = 2.0 static
coefficient of restitution for balls
Definition at line 361 of file FastFiz.h.
const double Pool::Ball::BALL_MASS = 163.01 static
5.57 oz.
ball mass [g]
Definition at line 363 of file FastFiz.h.
Referenced by Pool::CueStrikeEvent::doHandle().
const double Pool::Ball::BALL_RADIUS = 0.028575 static
2.25" ball radius [m]
Definition at line 364 of file FastFiz.h.
Referenced by Pool::Shot::getDuration().
const double Pool::Ball::MU_BALL_BALL = 0.01 static
coefficient of ball-ball friction
Definition at line 359 of file FastFiz.h.
const double Pool::Ball::MU_CUETIP_BALL = 0.7 static
coefficient of cue tip-ball friction
Definition at line 360 of file FastFiz.h.
The documentation for this class was generated from the following files:
FastFiz.h
FastFiz.cpp