FastFiz: Pool::Shot Class Reference
Pool::Shot Class Reference
Detailed result of a simulation of a shot.
#include <FastFiz.h>
Public Member Functions
const vector< Event * > & getEventList () const
Gets the list of events generated during the shot.
double getDuration () const
Returns the amount of time (in seconds) balls will take to settle after executing the shot.
~Shot ()
Destroy a shot object.
Friends
class TableState
Detailed Description
Detailed result of a simulation of a shot.
Public objects of this class can only be created by TableState::executeShot() Constructing a Shot object starts the physics simulation. The private methods in this class implement the main part of the physics simulation.
Definition at line 923 of file FastFiz.h.
Constructor & Destructor Documentation
Pool::Shot::~Shot ()
Destroy a shot object.
Deleting the Shot object is caller's responsibility.
Definition at line 971 of file FastFiz.cpp.
Member Function Documentation
double Pool::Shot::getDuration () const
Returns the amount of time (in seconds) balls will take to settle after executing the shot.
Definition at line 976 of file FastFiz.cpp.
References Pool::ShotParams::a, Pool::ShotParams::b, Pool::Event::BALL_COLLISION, Pool::Ball::BALL_RADIUS, Pool::Vector::cross(), Pool::Ball::CUE, Pool::Table::E, Pool::Event::eventCmp(), Pool::Utils::fequal(), Pool::Utils::fgreater(), Pool::TableState::fixOverlap(), Pool::Table::g, Pool::TableState::getBall(), Pool::TableState::getBegin(), Pool::TableState::getEnd(), Pool::Ball::getID(), Pool::Ball::getIDString(), Pool::Table::getLength(), Pool::Table::getMuRolling(), Pool::Table::getMuSliding(), Pool::Table::getMuSpinning(), Pool::Table::getPocketLeft(), Pool::Table::getPocketRight(), Pool::Ball::getPos(), Pool::Ball::getRadius(), Pool::Ball::getSpin(), Pool::Ball::getState(), Pool::TableState::getTable(), Pool::Event::getTime(), Pool::Ball::getVelocity(), Pool::Table::getWidth(), Pool::BadShotException::INVALID_CUE_PARAMS, Pool::TableState::isPhysicallyPossible(), Pool::TableState::isValidBallPlacement(), Pool::Vector::mag(), Pool::Table::N_RAIL, Pool::Table::NE, Pool::Table::NE_RAIL, Pool::Vector::norm(), Pool::Table::NW, Pool::Table::NW_RAIL, Pool::TableState::OK_PRECONDITION, Pool::Ball::ONE, Pool::ShotParams::phi, POOLFIZ_ERROR, Pool::BadShotException::POOLFIZ_ERROR, Pool::printOverlap(), Pool::Event::relatedTo(), Pool::Ball::ROLLING, Pool::Point::rotate(), Pool::Vector::rotate(), Pool::Table::S_RAIL, Pool::Table::SE, Pool::Table::SE_RAIL, Pool::Ball::setPos(), Pool::Ball::setSpin(), Pool::Ball::setVelocity(), Pool::Ball::SLIDING, Pool::Ball::SPINNING, Pool::Ball::STATIONARY, VirtualStopwatch::step(), VirtualStopwatch2::step(), Pool::Table::SW, Pool::Table::SW_RAIL, Pool::ShotParams::theta, Pool::Point::to_v(), Pool::TableState::toStream(), Pool::TableState::toString(), Pool::Ball::UNKNOWN_ID, Pool::Ball::updateState(), Pool::ShotParams::v, Pool::Table::W, Pool::Point::x, Pool::Vector::x, Pool::Point::y, Pool::Vector::y, and Pool::Vector::z.
Referenced by Pool::LogWriter::LogAndExecute().
const vector<Event*>& Pool::Shot::getEventList () const inline
Gets the list of events generated during the shot.
The vector is sorted by time, and all relevant ball information is available in the events.
Definition at line 931 of file FastFiz.h.
References Pool::operator<<().
Referenced by Pool::GameState::executeShot(), Pool::TableState::getFirstBallHit(), and Pool::operator<<().
Friends And Related Function Documentation
friend class TableState friend
Definition at line 926 of file FastFiz.h.
The documentation for this class was generated from the following files:
FastFiz.h
FastFiz.cpp