FastFiz: Pool::GameState Class Reference
Pool::GameState Class Reference abstract
This defines most of the information and functions necessary about the state of a game.
#include <Rules.h>
Public Member Functions
GameState (double timeleft=0.0, double timeleft_opp=0.0)
Create new game state.
GameState (string gameString)
Parse common part of GameState from string.
virtual bool isTerminal () const
Determines if the GameState is in a terminal state (i.e.
virtual bool positionRequired () const
Determines if the agent must provide a valid position for the cue ball.
virtual bool decisionAllowed () const
Determines if the agent is allowed to make a decision.
virtual bool shotRequired () const
Determines if the agent is required to provide a valid shot.
virtual string toString ()
Serializes the GameState as a string.
virtual void toStream (ostream &out) const
Exports the GameState to a stream.
virtual GameState * clone ()=0
Allocate a new copy of this GameState.
virtual GameType gameType () const =0
Returns the GameType of the GameState.
virtual const bool isOpenTable () const
Returns true if solids/stripes have not been determined yet.
virtual const TurnType getTurnType () const
virtual const bool playingSolids () const
Returns true if current player should shoot solids.
virtual const bool curPlayerStarted () const
Returns true if the current player had the inital break.
virtual const double timeLeft () const
Returns the amount of time left (in seconds) for the current player.
virtual const double timeLeftOpp () const
Returns the amount of time left (in seconds) for the other player.
virtual const TableState & tableState () const
Allows caller read-only access to the internal table state.
virtual ShotResult executeShot (const GameShot &shot, Shot **shotObj=NULL)
Calls the rules to check the shot values, executes the shot using the physics library, and then evalues the resulting GameState.
Static Public Member Functions
static GameState * Factory (istream &sourceStream)
Generate a new GameState object by reading information from an input stream.
static GameState * Factory (string sourceString)
Generate a new GameState object by reading information from an input string.
static GameState * RackedState (GameType gameType)
Returns a newly allocated racked (initial) state of a game by game type.
Protected Types
enum PreProcessCode { PPC_BADPARAMS =0, PPC_G_NOEXECUTE, PPC_G_NORMAL, PPC_G_PLACECUE }
Possible results of pre-evaluation of shot parameters for current game state.
Protected Member Functions
virtual bool isLegalTurnType () const
Returns true if the current turnType is defined for the current game.
virtual void importFromStream (istream &sourceStream)
Read common information from an input stream.
virtual PreProcessCode preProcess (const GameShot &shot)=0
Pre-evaluate shot parameters for the current game state.
virtual void processShot (const vector< Event * > &eventList, const GameShot &gameShot)=0
Called after shot execution to process an event list and adjust game state.
virtual void rack ()=0
Update TableState to the racked state, does NOT update other params.
virtual void switchSides ()
Utility function to switch the active player.
Protected Attributes
TableState _tableState
TurnType _turnType
double _timeLeft
double _timeLeftOpp
bool _curPlayerStarted
bool _switchedSides
Friends
ostream & operator<< (ostream &os, const GameState &obj)
Convienence parsing operators.
istream & operator>> (istream &is, GameState &obj)
Detailed Description
This defines most of the information and functions necessary about the state of a game.
All rules objects subclass off this.
Definition at line 99 of file Rules.h.
Member Enumeration Documentation
enum Pool::GameState::PreProcessCode protected
Possible results of pre-evaluation of shot parameters for current game state.
Enumerator
PPC_BADPARAMS
Shot parameters not satisfactory for game state.
PPC_G_NOEXECUTE
Decision information in shot is sufficient.
No need to execute shot.
PPC_G_NORMAL
Shot should be processed normally.
Cue ball is not to be moved.
PPC_G_PLACECUE
Shot should be processed normally.
Cue ball is to be placed at requested position.
Definition at line 262 of file Rules.h.
Constructor & Destructor Documentation
Pool::GameState::GameState (double timeleft = 0.0, double timeleft_opp = 0.0) inline explicit
Create new game state.
This function should not be called directly. Use Factory instead. Zero timeouts (default) mean no timeout.
Definition at line 137 of file Rules.h.
Pool::GameState::GameState (string gameString) inline
Parse common part of GameState from string.
Definition at line 144 of file Rules.h.
Member Function Documentation
virtual GameState* Pool::GameState::clone () pure virtual
Allocate a new copy of this GameState.
Implemented in Pool::NineBallState, and Pool::EightBallState.
Referenced by Pool::LogWriter::LogAndExecute().
virtual const bool Pool::GameState::curPlayerStarted () const inline virtual
Returns true if the current player had the inital break.
Definition at line 220 of file Rules.h.
virtual bool Pool::GameState::decisionAllowed () const inline virtual
Determines if the agent is allowed to make a decision.
Definition at line 161 of file Rules.h.
Referenced by Pool::AIBase::computeShot().
ShotResult GameState::executeShot (const GameShot & shot, Shot ** shotObj = NULL) virtual
Calls the rules to check the shot values, executes the shot using the physics library, and then evalues the resulting GameState.
Optionally, returns the Shot object used to execute the physical shot.
Parameters
shot Shot to execute
shotObj Pointer to an unallocated Shot* which will include a newly allocated Shot object. Caller is responsible to delete *shotObj after processing.
Definition at line 108 of file Rules.cpp.
References Pool::GameShot::cue_x, Pool::GameShot::cue_y, Pool::Shot::getEventList(), Pool::GameShot::params, Pool::SR_BAD_PARAMS, Pool::SR_OK, Pool::SR_OK_LOST_TURN, Pool::SR_SHOT_IMPOSSIBLE, Pool::SR_TIMEOUT, and Pool::GameShot::timeSpent.
Referenced by Pool::LogWriter::LogAndExecute().
GameState * GameState::Factory (istream & sourceStream) static
Generate a new GameState object by reading information from an input stream.
Game state should have been written with toStream or toString.
Definition at line 17 of file Rules.cpp.
References Pool::GT_EIGHTBALL, and Pool::GT_NINEBALL.
static GameState* Pool::GameState::Factory (string sourceString) inline static
Generate a new GameState object by reading information from an input string.
Game state should have been written with toStream or toString.
Definition at line 115 of file Rules.h.
virtual GameType Pool::GameState::gameType () const pure virtual
Returns the GameType of the GameState.
Implemented in Pool::NineBallState, and Pool::EightBallState.
Referenced by Pool::AIBase::computeShot().
virtual const TurnType Pool::GameState::getTurnType () const inline virtual
Definition at line 214 of file Rules.h.
void GameState::importFromStream (istream & sourceStream) protected virtual
Read common information from an input stream.
Reimplemented in Pool::NineBallState, and Pool::EightBallState.
Definition at line 81 of file Rules.cpp.
Referenced by RackedState().
virtual bool Pool::GameState::isLegalTurnType () const inline protected virtual
Returns true if the current turnType is defined for the current game.
Reimplemented in Pool::NineBallState, and Pool::EightBallState.
Definition at line 247 of file Rules.h.
References Pool::TT_BALL_IN_HAND, Pool::TT_BEHIND_LINE, Pool::TT_BREAK, Pool::TT_NORMAL, and Pool::TT_WIN.
Referenced by Pool::EightBallState::isLegalTurnType(), and Pool::NineBallState::isLegalTurnType().
virtual const bool Pool::GameState::isOpenTable () const inline virtual
Returns true if solids/stripes have not been determined yet.
Reimplemented in Pool::EightBallState.
Definition at line 213 of file Rules.h.
virtual bool Pool::GameState::isTerminal () const inline virtual
Determines if the GameState is in a terminal state (i.e.
the game is over.)
Definition at line 153 of file Rules.h.
References Pool::TT_RESERVED, and Pool::TT_WIN.
Referenced by Pool::AIBase::computeShot().
virtual const bool Pool::GameState::playingSolids () const inline virtual
Returns true if current player should shoot solids.
Only meaningful if isOpenTable is false.
Reimplemented in Pool::EightBallState.
Definition at line 218 of file Rules.h.
virtual bool Pool::GameState::positionRequired () const inline virtual
Determines if the agent must provide a valid position for the cue ball.
Definition at line 157 of file Rules.h.
References Pool::TT_BALL_IN_HAND, Pool::TT_BEHIND_LINE, and Pool::TT_BREAK.
virtual PreProcessCode Pool::GameState::preProcess (const GameShot & shot) protected pure virtual
Pre-evaluate shot parameters for the current game state.
Implemented in Pool::NineBallState, and Pool::EightBallState.
virtual void Pool::GameState::processShot (const vector< Event * > & eventList, const GameShot & gameShot) protected pure virtual
Called after shot execution to process an event list and adjust game state.
Implemented in Pool::NineBallState, and Pool::EightBallState.
virtual void Pool::GameState::rack () protected pure virtual
Update TableState to the racked state, does NOT update other params.
Implemented in Pool::NineBallState, and Pool::EightBallState.
GameState * GameState::RackedState (GameType gameType) static
Returns a newly allocated racked (initial) state of a game by game type.
Definition at line 47 of file Rules.cpp.
References Pool::GT_EIGHTBALL, importFromStream(), Pool::operator<<(), Pool::operator>>(), and toStream().
virtual bool Pool::GameState::shotRequired () const inline virtual
Determines if the agent is required to provide a valid shot.
Reimplemented in Pool::NineBallState, and Pool::EightBallState.
Definition at line 165 of file Rules.h.
References Pool::operator<<(), and Pool::operator>>().
Referenced by Pool::AIBase::computeShot(), Pool::EightBallState::shotRequired(), and Pool::NineBallState::shotRequired().
void GameState::switchSides () protected virtual
Utility function to switch the active player.
Reimplemented in Pool::NineBallState, and Pool::EightBallState.
Definition at line 164 of file Rules.cpp.
virtual const TableState& Pool::GameState::tableState () const inline virtual
Allows caller read-only access to the internal table state.
Definition at line 226 of file Rules.h.
Referenced by main().
virtual const double Pool::GameState::timeLeft () const inline virtual
Returns the amount of time left (in seconds) for the current player.
Definition at line 222 of file Rules.h.
virtual const double Pool::GameState::timeLeftOpp () const inline virtual
Returns the amount of time left (in seconds) for the other player.
Definition at line 224 of file Rules.h.
void GameState::toStream (ostream & out) const virtual
Exports the GameState to a stream.
Reimplemented in Pool::NineBallState, and Pool::EightBallState.
Definition at line 96 of file Rules.cpp.
Referenced by RackedState().
string GameState::toString () virtual
Serializes the GameState as a string.
Definition at line 89 of file Rules.cpp.
Friends And Related Function Documentation
ostream& operator<< (ostream & os, const GameState & obj) friend
Convienence parsing operators.
istream& operator>> (istream & is, GameState & obj) friend
Member Data Documentation
bool Pool::GameState::_curPlayerStarted protected
Definition at line 286 of file Rules.h.
bool Pool::GameState::_switchedSides protected
Definition at line 287 of file Rules.h.
TableState Pool::GameState::_tableState protected
Definition at line 283 of file Rules.h.
double Pool::GameState::_timeLeft protected
Definition at line 285 of file Rules.h.
double Pool::GameState::_timeLeftOpp protected
Definition at line 285 of file Rules.h.
TurnType Pool::GameState::_turnType protected
Definition at line 284 of file Rules.h.
The documentation for this class was generated from the following files:
Rules.h
Rules.cpp