FastFiz: Pool::Event Class Reference
Pool::Event Class Reference abstract
Base class of the Event heirarchy.
#include <FastFiz.h>
Public Types
enum Type {
NO_EVENT, STATE_CHANGE, BALL_COLLISION, RAIL_COLLISION,
POCKETED, CUE_STRIKE, MISCUE, UNKNOWN_EVENT
}
Indicates the type of event.
Public Member Functions
Event (double time, Ball::Type b)
Create a new base event.
double getTime () const
Returns the event's simulation time index.
Ball::Type getBall1 () const
Returns the id of first (possibly only) ball involved in the event.
Ball & getBall1Data ()
Returns the physical information (location, velocity,spin) of the first (possibly only) ball involved in the event.
bool operator< (const Event &other) const
Sorts Events by time.
string toString () const
Returns a human-readble string representation of the event.
virtual Type getType () const
Returns the type of the event.
virtual string getTypeString () const
Returns the type of the event as a string.
virtual Ball::Type getBall2 () const
Returns the id of the second ball involved in the event, if applicable.
virtual Ball & getBall2Data ()
Returns the physical information (location, velocity,spin) of the second ball involved in the event.
virtual bool relatedTo (const Event &other) const
Returns true if this event and the other event affect a shared ball.
virtual bool involvesBall (Ball::Type b) const
Returns true if this event affects specified ball.
virtual ~Event ()
Destructor.
void handle (TableState &ts, bool VERBOSE=false)
Used within physics code to apply event to a table state, modifying ball states, positions, and properties Also updates ball information within event.
Static Public Member Functions
static bool eventCmp (const Event *event1, const Event *event2)
Event comparison function, calls operator<.
Protected Member Functions
virtual void doHandle (TableState &ts, bool VERBOSE) const =0
virtual void copyBalls (TableState &ts)
virtual ostream & dump (ostream &out) const
Protected Attributes
double _time
Ball::Type _ball1
Ball * _ball1Data
Friends
ostream & operator<< (ostream &out, const Event &rhs)
Detailed Description
Base class of the Event heirarchy.
Indicates a notable event in the execution of a shot.
Subclasses of this class indicate specific events.
Definition at line 708 of file FastFiz.h.
Member Enumeration Documentation
enum Pool::Event::Type
Indicates the type of event.
Enumerator
NO_EVENT
Nothing happened (only used internally)
STATE_CHANGE
A ball transitioned to a different motion state.
BALL_COLLISION
two balls collided
RAIL_COLLISION
a ball collided with a rail
POCKETED
a ball was pocketed
CUE_STRIKE
the cue ball was struck by the cue stick successfully
MISCUE
the cue ball was struck by the cue stick unsuccessfully
UNKNOWN_EVENT
an unknown event
Definition at line 715 of file FastFiz.h.
Constructor & Destructor Documentation
Pool::Event::Event (double time, Ball::Type b) inline
Create a new base event.
Parameters
time Simulation time event took place.
b id of the ball affected by the event.
Definition at line 729 of file FastFiz.h.
virtual Pool::Event::~Event () inline virtual
Destructor.
Definition at line 765 of file FastFiz.h.
Member Function Documentation
void Pool::Event::copyBalls (TableState & ts) protected virtual
Reimplemented in Pool::BallCollisionEvent.
Definition at line 894 of file FastFiz.cpp.
References Pool::TableState::getBall().
Referenced by Pool::BallCollisionEvent::copyBalls().
virtual void Pool::Event::doHandle (TableState & ts, bool VERBOSE) const protected pure virtual
Implemented in Pool::CueStrikeEvent, Pool::PocketedEvent, Pool::RailCollisionEvent, Pool::BallCollisionEvent, and Pool::StateChangeEvent.
ostream & Pool::Event::dump (ostream & out) const protected virtual
Reimplemented in Pool::CueStrikeEvent, Pool::PocketedEvent, Pool::RailCollisionEvent, and Pool::BallCollisionEvent.
Definition at line 918 of file FastFiz.cpp.
References Pool::Ball::getIDString().
Referenced by Pool::BallCollisionEvent::dump(), Pool::RailCollisionEvent::dump(), Pool::PocketedEvent::dump(), Pool::CueStrikeEvent::dump(), and Pool::operator<<().
bool Pool::Event::eventCmp (const Event * event1, const Event * event2) static
Event comparison function, calls operator<.
Definition at line 671 of file FastFiz.cpp.
Referenced by Pool::Shot::getDuration().
Ball::Type Pool::Event::getBall1 () const inline
Returns the id of first (possibly only) ball involved in the event.
Definition at line 735 of file FastFiz.h.
Ball& Pool::Event::getBall1Data () inline
Returns the physical information (location, velocity,spin) of the first (possibly only) ball involved in the event.
May cause a null pointer exception if the information is not available (if event was not yet handled).
Definition at line 739 of file FastFiz.h.
virtual Ball::Type Pool::Event::getBall2 () const inline virtual
Returns the id of the second ball involved in the event, if applicable.
Reimplemented in Pool::BallCollisionEvent.
Definition at line 754 of file FastFiz.h.
virtual Ball& Pool::Event::getBall2Data () inline virtual
Returns the physical information (location, velocity,spin) of the second ball involved in the event.
If no second ball is involved, will return the first ball information. May cause a null pointer exception if the information is not available (if event was not yet handled).
Reimplemented in Pool::BallCollisionEvent.
Definition at line 759 of file FastFiz.h.
double Pool::Event::getTime () const inline
Returns the event's simulation time index.
Definition at line 732 of file FastFiz.h.
Referenced by Pool::Shot::getDuration().
virtual Type Pool::Event::getType () const inline virtual
Returns the type of the event.
Reimplemented in Pool::CueStrikeEvent, Pool::PocketedEvent, Pool::RailCollisionEvent, Pool::BallCollisionEvent, and Pool::StateChangeEvent.
Definition at line 750 of file FastFiz.h.
virtual string Pool::Event::getTypeString () const inline virtual
Returns the type of the event as a string.
Reimplemented in Pool::CueStrikeEvent, Pool::PocketedEvent, Pool::RailCollisionEvent, Pool::BallCollisionEvent, and Pool::StateChangeEvent.
Definition at line 752 of file FastFiz.h.
void Pool::Event::handle (TableState & ts, bool VERBOSE = false) inline
Used within physics code to apply event to a table state, modifying ball states, positions, and properties Also updates ball information within event.
Definition at line 770 of file FastFiz.h.
bool Pool::Event::involvesBall (Ball::Type b) const virtual
Returns true if this event affects specified ball.
Reimplemented in Pool::BallCollisionEvent.
Definition at line 679 of file FastFiz.cpp.
Referenced by relatedTo(), and Pool::BallCollisionEvent::relatedTo().
bool Pool::Event::operator< (const Event & other) const
Sorts Events by time.
Definition at line 667 of file FastFiz.cpp.
References _time.
bool Pool::Event::relatedTo (const Event & other) const virtual
Returns true if this event and the other event affect a shared ball.
Reimplemented in Pool::BallCollisionEvent.
Definition at line 675 of file FastFiz.cpp.
References involvesBall().
Referenced by Pool::Shot::getDuration().
string Pool::Event::toString () const
Returns a human-readble string representation of the event.
Definition at line 905 of file FastFiz.cpp.
Friends And Related Function Documentation
ostream& operator<< (ostream & out, const Event & rhs) friend
Definition at line 911 of file FastFiz.cpp.
Member Data Documentation
Ball::Type Pool::Event::_ball1 protected
Definition at line 773 of file FastFiz.h.
Ball* Pool::Event::_ball1Data protected
Definition at line 774 of file FastFiz.h.
double Pool::Event::_time protected
Definition at line 772 of file FastFiz.h.
Referenced by operator<().
The documentation for this class was generated from the following files:
FastFiz.h
FastFiz.cpp