FastFiz: Pool::Utils Class Reference
Pool::Utils Class Reference
General utility functions.
#include <FastFiz.h>
Public Types
enum ANGLE_RANGE { START_ZERO, START_NEG_HALF_CIRCLE }
enum ANGLE_UNIT { DEGREES, RADIANS }
Static Public Member Functions
static double angle (Point p1, Point p2, ANGLE_RANGE range, ANGLE_UNIT unit)
direction in the plane from p1 to p2
static double toDegrees (double angleRad)
converts radians to degrees
static double normalizeRadianAngleRange (double angle, ANGLE_RANGE range)
converts an angle in radians to be on the specified range, either [0,2*pi) or [-pi,pi)
static gsl_rng * rng ()
A random number generator instance.
static bool fequal (double a, double b)
Equality test for doubles.
static bool fless (double a, double b)
Less than test for doubles.
static bool fgreater (double a, double b)
Greater than test for doubles.
static bool fgreaterequal (double a, double b)
Greater than or equal test for doubles.
static bool flessequal (double a, double b)
Less than or equal test for doubles.
static bool vzero (double a)
Check if velocity absolute value should be considered zero.
Static Public Attributes
static const double EPSILON = 1.0E-11
double comparison threshold
static const double VELOCITY_EPSILON = 1E-10
threshold velocity for balls to be considered stationary.
Detailed Description
General utility functions.
Definition at line 316 of file FastFiz.h.
Member Enumeration Documentation
enum Pool::Utils::ANGLE_RANGE
Enumerator
START_ZERO
START_NEG_HALF_CIRCLE
Definition at line 322 of file FastFiz.h.
enum Pool::Utils::ANGLE_UNIT
Enumerator
DEGREES
RADIANS
Definition at line 323 of file FastFiz.h.
Member Function Documentation
double Pool::Utils::angle (Point p1, Point p2, ANGLE_RANGE range, ANGLE_UNIT unit) inline static
direction in the plane from p1 to p2
Definition at line 82 of file FastFiz.cpp.
References normalizeRadianAngleRange(), RADIANS, toDegrees(), Pool::Point::x, and Pool::Point::y.
Referenced by Pool::BallCollisionEvent::doHandle(), and normalizeRadianAngleRange().
bool Pool::Utils::fequal (double a, double b) inline static
Equality test for doubles.
Definition at line 61 of file FastFiz.cpp.
References EPSILON.
Referenced by fgreater(), fgreaterequal(), fless(), flessequal(), and Pool::Shot::getDuration().
bool Pool::Utils::fgreater (double a, double b) inline static
Greater than test for doubles.
Definition at line 69 of file FastFiz.cpp.
References fequal().
Referenced by Pool::TableState::fromString(), Pool::Shot::getDuration(), Pool::TableState::isPhysicallyPossible(), and Pool::TableState::isValidBallPlacement().
bool Pool::Utils::fgreaterequal (double a, double b) inline static
Greater than or equal test for doubles.
Definition at line 73 of file FastFiz.cpp.
References fequal().
bool Pool::Utils::fless (double a, double b) inline static
Less than test for doubles.
Definition at line 65 of file FastFiz.cpp.
References fequal().
Referenced by Pool::TableState::fromString(), Pool::TableState::isPhysicallyPossible(), and Pool::TableState::isValidBallPlacement().
bool Pool::Utils::flessequal (double a, double b) inline static
Less than or equal test for doubles.
Definition at line 77 of file FastFiz.cpp.
References fequal().
Referenced by Pool::TableState::isPhysicallyPossible().
double Pool::Utils::normalizeRadianAngleRange (double angle, ANGLE_RANGE range) static
converts an angle in radians to be on the specified range, either [0,2*pi) or [-pi,pi)
Definition at line 93 of file FastFiz.cpp.
References angle(), and START_NEG_HALF_CIRCLE.
Referenced by angle().
gsl_rng * Pool::Utils::rng () static
A random number generator instance.
gsl_rng_default_seed
Definition at line 2736 of file FastFiz.cpp.
Referenced by Pool::Ball::addNoise(), and Pool::TableState::randomize().
double Pool::Utils::toDegrees (double angleRad) inline static
converts radians to degrees
Definition at line 52 of file FastFiz.cpp.
Referenced by angle().
bool Pool::Utils::vzero (double a) inline static
Check if velocity absolute value should be considered zero.
Definition at line 57 of file FastFiz.cpp.
References VELOCITY_EPSILON.
Referenced by Pool::BallCollisionEvent::doHandle(), and Pool::Ball::updateState().
Member Data Documentation
const double Pool::Utils::EPSILON = 1.0E-11 static
double comparison threshold
Definition at line 318 of file FastFiz.h.
Referenced by fequal(), and Pool::TableState::fixOverlap().
const double Pool::Utils::VELOCITY_EPSILON = 1E-10 static
threshold velocity for balls to be considered stationary.
Definition at line 319 of file FastFiz.h.
Referenced by vzero().
The documentation for this class was generated from the following files:
FastFiz.h
FastFiz.cpp