FastFiz: Pool::Table Class Reference
Pool::Table Class Reference
Class representing physical properties of a pool table.
#include <FastFiz.h>
Public Types
enum BoundaryId {
SW_POCKET, SW_RAIL, W_POCKET, NW_RAIL,
NW_POCKET, N_RAIL, NE_POCKET, NE_RAIL,
E_POCKET, SE_RAIL, SE_POCKET, S_RAIL,
UNKNOWN_BOUNDARY
}
A rail or a pocket.
enum Pocket {
SW, W, NW, NE,
E, SE, UNKNOWN_POCKET
}
Public Member Functions
Table ()
Constructs a table with the default parameters.
Table (double length, double width, double cornerPocketWidth, double sidePocketWidth, double muS, double muR, double muSp, double railHeight, double cueLength, double railVelDampingX, double railVelDampingY, double railSpinDamping, double railZSpinAngleAdj, double railVelAngleAdj)
Constructs a table with the given parameters and automatically sets the pockets.
Table (const Table &rhs)
Copy constructor.
const Table & operator= (const Table &rhs)
Assignment operator.
double getLength () const
Returns the length of the table (in metres).
double getWidth () const
Returns the width of the table (in metres).
double getHeadString () const
Returns the y-coordinate of the headstring of the table (in metres)
const Point & getFootSpot () const
Returns the x-y coordinate of the footspot of the table (in metres)
void setCueLength (double length)
Sets the length of the cue stick.
double getCueLength () const
Returns the length of the cue stick.
void setRailHeight (double height)
Sets the height of the rails around the table.
double getRailHeight () const
Returns the height of the rails around the table.
void setMuSliding (double mu)
Sets the coefficient of sliding friction.
double getMuSliding () const
Returns the coefficient of sliding friction.
void setMuRolling (double mu)
Sets the coefficient of rolling friction.
double getMuRolling () const
Returns the coefficient of rolling friction.
void setMuSpinning (double mu)
Sets the coefficient of spinning friction.
double getMuSpinning () const
Returns the coefficient of spinning friction.
const Point & getPocketCenter (Pocket pocket) const
Returns the aiming point of the given pocket (in metres).
const Point & getPocketRight (Pocket pocket) const
Returns the right corner coordinates of the given pocket (in metres), looking at the pocket from the center of the table.
const Point & getPocketLeft (Pocket pocket) const
Returns the left corner coordinates of the given pocket (in metres), looking at the pocket from the center of the table.
Static Public Member Functions
static const Table & defaultTable ()
Contains a single default table object whose reference is returned when called.
static Ball::State stateFromPocket (Pocket pocket)
Returns the pocketed ball state corresponding to the given pocket (by Pocket)
static Pocket pocketFromBndId (BoundaryId bnd)
Returns the same pocket in Pocket form rather than BoundaryId form.
static BoundaryId bndIdFromPocket (Pocket pocket)
Returns the same pocket in BoundaryId form rather than Pocket form.
static string boundaryName (BoundaryId boundary)
returns a string of the boundary name
static string pocketName (Pocket pocket)
returns a string of the pocket name
Static Public Attributes
static const double g = 9.81
Gravitational constant.
static const double MU_SLIDING = 0.2
coefficient of sliding friction
static const double MU_ROLLING = 0.015
coefficient of rolling friction
static const double MU_SPINNING = 0.044
coefficient of spinning friction
static const double TABLE_LENGTH = 2.236
table length [m]
static const double TABLE_WIDTH = 1.116
table width [m]
static const double CORNER_POCKET_WIDTH = 0.11
corner pocket width [m]
static const double SIDE_POCKET_WIDTH = 0.12
side pocket width [m]
static const double RAIL_HEIGHT = 0.040005
rail height [m]
static const double CUE_LENGTH = 1.45
cue length [m]
static const double RAIL_VEL_DAMPING_X = 0.6
damping factor for velocity component parallel to rail
static const double RAIL_VEL_DAMPING_Y = 0.9
damping factor for velocity component perpendicular to rail
static const double RAIL_SPIN_DAMPING = 0.1
damping factor for angular velocity component
static const double RAIL_VEL_ANGLE_ADJ = 0.0
angle adjustment factor for velocity vector
static const double RAIL_ZSPIN_ANGLE_ADJ = 0.0
angle adjustment factor for vertical component of angular velocity vector
static const double CUE_MASS = 160.0 / 0.302631579
Derived from poolfiz results.
static const double I = 0.4*160.0*0.028575*0.028575*0.995473
moment of inertia; to match poolfiz
Detailed Description
Class representing physical properties of a pool table.
This does not include the position of the balls. In general, this object doesn't need to be instansiated more than once. This class also provides some static utility functions and constants related to the pool table.
Definition at line 501 of file FastFiz.h.
Member Enumeration Documentation
enum Pool::Table::BoundaryId
A rail or a pocket.
Enumerator
SW_POCKET
SW_RAIL
W_POCKET
NW_RAIL
NW_POCKET
N_RAIL
NE_POCKET
NE_RAIL
E_POCKET
SE_RAIL
SE_POCKET
S_RAIL
UNKNOWN_BOUNDARY
Definition at line 528 of file FastFiz.h.
enum Pool::Table::Pocket
Enumerator
SW
W
NW
NE
E
SE
UNKNOWN_POCKET
Definition at line 531 of file FastFiz.h.
Constructor & Destructor Documentation
Pool::Table::Table () inline
Constructs a table with the default parameters.
Definition at line 534 of file FastFiz.h.
Pool::Table::Table (double length, double width, double cornerPocketWidth, double sidePocketWidth, double muS, double muR, double muSp, double railHeight, double cueLength, double railVelDampingX, double railVelDampingY, double railSpinDamping, double railZSpinAngleAdj, double railVelAngleAdj)
Constructs a table with the given parameters and automatically sets the pockets.
Parameters
length the length of the table in metres
width the width of the table in metres
cornerPocketWidth the width of corner pockets (horn to horn) in metres
sidePocketWidth the width of the side pockets (horn to horn) in metres
muS the coefficient of sliding friction (dimensionless)
muR the coefficient of rolling friction (dimensionless)
muSp the coefficient of spinning friction (dimensionless)
railHeight the height of the top of the rail above the table in metres
cueLength the length of the cue in metres
railVelDampingX velocity damping factor of the banks (X)
railVelDampingY velocity damping factor of the banks (Y)
railSpinDamping spin damping factor of the banks
railZSpinAngleAdj z-spin angle of deflection factor of the banks
railVelAngleAdj velocity deflection factor of the banks
Definition at line 418 of file FastFiz.cpp.
Pool::Table::Table (const Table & rhs)
Copy constructor.
Definition at line 446 of file FastFiz.cpp.
Member Function Documentation
Table::BoundaryId Pool::Table::bndIdFromPocket (Pocket pocket) static
Returns the same pocket in BoundaryId form rather than Pocket form.
Definition at line 617 of file FastFiz.cpp.
References E, E_POCKET, NE, NE_POCKET, NW, NW_POCKET, SE, SE_POCKET, SW, SW_POCKET, UNKNOWN_BOUNDARY, W, and W_POCKET.
string Pool::Table::boundaryName (BoundaryId boundary) static
returns a string of the boundary name
Definition at line 631 of file FastFiz.cpp.
References E_POCKET, N_RAIL, NE_POCKET, NE_RAIL, NW_POCKET, NW_RAIL, S_RAIL, SE_POCKET, SE_RAIL, SW_POCKET, SW_RAIL, UNKNOWN_BOUNDARY, and W_POCKET.
Referenced by Pool::RailCollisionEvent::doHandle(), and Pool::RailCollisionEvent::dump().
static const Table& Pool::Table::defaultTable () inline static
Contains a single default table object whose reference is returned when called.
Definition at line 648 of file FastFiz.h.
double Pool::Table::getCueLength () const inline
Returns the length of the cue stick.
Definition at line 606 of file FastFiz.h.
const Point& Pool::Table::getFootSpot () const inline
Returns the x-y coordinate of the footspot of the table (in metres)
Definition at line 599 of file FastFiz.h.
Referenced by Pool::EightBallState::rack(), and Pool::NineBallState::rack().
double Pool::Table::getHeadString () const inline
Returns the y-coordinate of the headstring of the table (in metres)
Definition at line 596 of file FastFiz.h.
Referenced by Pool::EightBallState::rack(), and Pool::NineBallState::rack().
double Pool::Table::getLength () const inline
Returns the length of the table (in metres).
Definition at line 590 of file FastFiz.h.
Referenced by Pool::Shot::getDuration().
double Pool::Table::getMuRolling () const inline
Returns the coefficient of rolling friction.
Definition at line 627 of file FastFiz.h.
Referenced by Pool::Shot::getDuration().
double Pool::Table::getMuSliding () const inline
Returns the coefficient of sliding friction.
Definition at line 620 of file FastFiz.h.
Referenced by Pool::Shot::getDuration().
double Pool::Table::getMuSpinning () const inline
Returns the coefficient of spinning friction.
Definition at line 634 of file FastFiz.h.
Referenced by Pool::Shot::getDuration().
const Point & Pool::Table::getPocketCenter (Pocket pocket) const
Returns the aiming point of the given pocket (in metres).
Definition at line 546 of file FastFiz.cpp.
References E, NE, NW, SE, SW, and W.
const Point & Pool::Table::getPocketLeft (Pocket pocket) const
Returns the left corner coordinates of the given pocket (in metres), looking at the pocket from the center of the table.
Definition at line 574 of file FastFiz.cpp.
References E, NE, NW, SE, SW, and W.
Referenced by Pool::Shot::getDuration().
const Point & Pool::Table::getPocketRight (Pocket pocket) const
Returns the right corner coordinates of the given pocket (in metres), looking at the pocket from the center of the table.
Definition at line 560 of file FastFiz.cpp.
References E, NE, NW, SE, SW, and W.
Referenced by Pool::Shot::getDuration().
double Pool::Table::getRailHeight () const inline
Returns the height of the rails around the table.
Definition at line 613 of file FastFiz.h.
double Pool::Table::getWidth () const inline
Returns the width of the table (in metres).
Definition at line 593 of file FastFiz.h.
Referenced by Pool::Shot::getDuration(), Pool::EightBallState::rack(), and Pool::NineBallState::rack().
const Table & Pool::Table::operator= (const Table & rhs)
Assignment operator.
Definition at line 508 of file FastFiz.cpp.
Table::Pocket Pool::Table::pocketFromBndId (BoundaryId bnd) static
Returns the same pocket in Pocket form rather than BoundaryId form.
Definition at line 603 of file FastFiz.cpp.
References E, E_POCKET, NE, NE_POCKET, NW, NW_POCKET, SE, SE_POCKET, SW, SW_POCKET, UNKNOWN_POCKET, W, and W_POCKET.
string Pool::Table::pocketName (Pocket pocket) static
returns a string of the pocket name
Definition at line 652 of file FastFiz.cpp.
References E, NE, NW, SE, SW, UNKNOWN_POCKET, and W.
Referenced by Pool::PocketedEvent::doHandle(), and Pool::PocketedEvent::dump().
void Pool::Table::setCueLength (double length) inline
Sets the length of the cue stick.
Parameters
length the length of the cue in metres.
Definition at line 603 of file FastFiz.h.
void Pool::Table::setMuRolling (double mu) inline
Sets the coefficient of rolling friction.
Parameters
mu the coefficient of rolling friction (between 0 and 1).
Definition at line 624 of file FastFiz.h.
void Pool::Table::setMuSliding (double mu) inline
Sets the coefficient of sliding friction.
Parameters
mu the coefficient of sliding friction (between 0 and 1).
Definition at line 617 of file FastFiz.h.
void Pool::Table::setMuSpinning (double mu) inline
Sets the coefficient of spinning friction.
Parameters
mu the coefficient of spinning friction (between 0 and 1).
Definition at line 631 of file FastFiz.h.
void Pool::Table::setRailHeight (double height) inline
Sets the height of the rails around the table.
Parameters
height the height of the rails in metres.
Definition at line 610 of file FastFiz.h.
Ball::State Pool::Table::stateFromPocket (Pocket pocket) static
Returns the pocketed ball state corresponding to the given pocket (by Pocket)
Definition at line 589 of file FastFiz.cpp.
References E, NE, NW, Pool::Ball::POCKETED_E, Pool::Ball::POCKETED_NE, Pool::Ball::POCKETED_NW, Pool::Ball::POCKETED_SE, Pool::Ball::POCKETED_SW, Pool::Ball::POCKETED_W, SE, SW, Pool::Ball::UNKNOWN_STATE, and W.
Referenced by Pool::PocketedEvent::doHandle().
Member Data Documentation
const double Pool::Table::CORNER_POCKET_WIDTH = 0.11 static
corner pocket width [m]
Definition at line 513 of file FastFiz.h.
const double Pool::Table::CUE_LENGTH = 1.45 static
cue length [m]
Definition at line 516 of file FastFiz.h.
const double Pool::Table::CUE_MASS = 160.0 / 0.302631579 static
Derived from poolfiz results.
Definition at line 524 of file FastFiz.h.
Referenced by Pool::CueStrikeEvent::doHandle().
const double Pool::Table::g = 9.81 static
Gravitational constant.
Definition at line 505 of file FastFiz.h.
Referenced by Pool::Shot::getDuration().
const double Pool::Table::I = 0.4*160.0*0.028575*0.028575*0.995473 static
moment of inertia; to match poolfiz
Definition at line 525 of file FastFiz.h.
Referenced by Pool::CueStrikeEvent::doHandle().
const double Pool::Table::MU_ROLLING = 0.015 static
coefficient of rolling friction
Definition at line 507 of file FastFiz.h.
const double Pool::Table::MU_SLIDING = 0.2 static
coefficient of sliding friction
Definition at line 506 of file FastFiz.h.
const double Pool::Table::MU_SPINNING = 0.044 static
coefficient of spinning friction
Definition at line 508 of file FastFiz.h.
const double Pool::Table::RAIL_HEIGHT = 0.040005 static
rail height [m]
Definition at line 515 of file FastFiz.h.
const double Pool::Table::RAIL_SPIN_DAMPING = 0.1 static
damping factor for angular velocity component
Definition at line 519 of file FastFiz.h.
const double Pool::Table::RAIL_VEL_ANGLE_ADJ = 0.0 static
angle adjustment factor for velocity vector
Definition at line 520 of file FastFiz.h.
const double Pool::Table::RAIL_VEL_DAMPING_X = 0.6 static
damping factor for velocity component parallel to rail
Definition at line 517 of file FastFiz.h.
const double Pool::Table::RAIL_VEL_DAMPING_Y = 0.9 static
damping factor for velocity component perpendicular to rail
Definition at line 518 of file FastFiz.h.
const double Pool::Table::RAIL_ZSPIN_ANGLE_ADJ = 0.0 static
angle adjustment factor for vertical component of angular velocity vector
Definition at line 521 of file FastFiz.h.
const double Pool::Table::SIDE_POCKET_WIDTH = 0.12 static
side pocket width [m]
Definition at line 514 of file FastFiz.h.
const double Pool::Table::TABLE_LENGTH = 2.236 static
table length [m]
Definition at line 511 of file FastFiz.h.
const double Pool::Table::TABLE_WIDTH = 1.116 static
table width [m]
Definition at line 512 of file FastFiz.h.
The documentation for this class was generated from the following files:
FastFiz.h
FastFiz.cpp