FastFiz: Pool::TableState Class Reference
Pool::TableState Class Reference
The physical state of balls on a table.
#include <FastFiz.h>
Public Member Functions
TableState (const Table &table=Table::defaultTable())
Create an empty table state for given table (or default table if not specified)
TableState (const TableState &rhs)
Copy constructor.
TableState & operator= (const TableState &rhs)
Assignment operator.
int getNumBalls () const
Return the number of different balls used in representing this state.
vector< Ball >::iterator getBegin ()
Iterator for start of ball vector.
vector< Ball >::iterator getEnd ()
Iterator for end of ball vector.
vector< Ball >::const_iterator getBegin () const
Const Iterator for start of ball vector.
vector< Ball >::const_iterator getEnd () const
Const Iterator for end of ball vector.
void fixOverlap (const bool VERBOSE)
void setBall (Ball &b)
Modify specified ball id with specified ball information, adding if needed.
void setBall (Ball::Type btype, Ball::State state, Point r)
Set a ball's state and position, adding if needed.
void setBall (Ball::Type btype, Ball::State state, double x, double y)
Set a ball's state and position, adding if needed.
void spotBall (Ball::Type btype, double dither=DITHER)
Spot a pocketed ball at or near the foot spot, with dithering if needed.
Ball & getBall (Ball::Type btype)
Get ball information based on id.
const Ball & getBall (Ball::Type btype) const
Get ball information based on id.
const Table & getTable () const
Return the underlying table object.
int isValidBallPlacement (bool VERBOSE=false) const
Returns BAD_X_VAL or BAD_Y_VAL if any ball that is in play is off the table or BALL_OVERLAP if any ball is overlapping with another ball.
int isPhysicallyPossible (const ShotParams &shotParams, bool VERBOSE=false) const
Checks physical validity of the given shot parameters and table state.
void addNoise (double dither)
Add racking noise to table state.
void randomize ()
Randomly position all balls on the table.
Shot * executeShot (const ShotParams &sp, bool verbose=false, bool errors=false)
Execute given shot on the table state.
Ball::Type getFirstBallHit (const ShotParams &sp)
Return the first ball hit by the cue ball while executing shot.
void toStream (ostream &out) const
Writes a machine-readable representation of the table state to a stream.
void fromStream (istream &in)
Reads a machine-readable representation of the table state from a stream.
string toString () const
Returns a machine-readable representation of the table state as a string.
void fromString (const string &s)
Reads a machine-readable representation of the table state from a string.
Static Public Attributes
static const double MAX_VELOCITY = 10
maximum velocity allowed [m/s]
static const double MIN_THETA = 0.0
minimum theta allowed [degrees]
static const double MAX_THETA = 70.0
maximum theta allowed [degrees]
static const int OK_PRECONDITION = 0
This integer is used within the bitmask integer returned by Table::isPhysicallyPossible() and Table::isValidBallPlacement() (as well as the fizG versions of those classes).
static const int BAD_A_VAL = 1
This integer is used within the bitmask integer returned by Table::isPhysicallyPossible() and Table::isValidBallPlacement() (as well as the fizG versions of those classes).
static const int BAD_B_VAL = 2
This integer is used within the bitmask integer returned by Table::isPhysicallyPossible() and Table::isValidBallPlacement() (as well as the fizG versions of those classes).
static const int BAD_THETA_VAL = 4
This integer is used within the bitmask integer returned by Table::isPhysicallyPossible() and Table::isValidBallPlacement() (as well as the fizG versions of those classes).
static const int BAD_PHI_VAL = 8
This integer is used within the bitmask integer returned by Table::isPhysicallyPossible() and Table::isValidBallPlacement() (as well as the fizG versions of those classes).
static const int BAD_V_VAL = 16
This integer is used within the bitmask integer returned by Table::isPhysicallyPossible() and Table::isValidBallPlacement() (as well as the fizG versions of those classes).
static const int BAD_X_VAL = 32
This integer is used within the bitmask integer returned by Table::isPhysicallyPossible() and Table::isValidBallPlacement() (as well as the fizG versions of those classes).
static const int BAD_Y_VAL = 64
This integer is used within the bitmask integer returned by Table::isPhysicallyPossible() and Table::isValidBallPlacement() (as well as the fizG versions of those classes).
static const int CUE_STICK_COLLISION = 128
This integer is used within the bitmask integer returned by Table::isPhysicallyPossible() and Table::isValidBallPlacement() (as well as the fizG versions of those classes).
static const int BALL_OVERLAP = 256
This integer is used within the bitmask integer returned by Table::isPhysicallyPossible() and Table::isValidBallPlacement() (as well as the fizG versions of those classes).
Detailed Description
The physical state of balls on a table.
Includes position and velocity information but no rules related information.
Definition at line 1003 of file FastFiz.h.
Constructor & Destructor Documentation
Pool::TableState::TableState (const Table & table = Table::defaultTable()) inline
Create an empty table state for given table (or default table if not specified)
Definition at line 1111 of file FastFiz.h.
Pool::TableState::TableState (const TableState & rhs) inline
Copy constructor.
Definition at line 1113 of file FastFiz.h.
Member Function Documentation
void Pool::TableState::addNoise (double dither)
Add racking noise to table state.
This has nothing to do with shot execution noise.
Definition at line 2495 of file FastFiz.cpp.
References getBegin(), getEnd(), and isValidBallPlacement().
Shot* Pool::TableState::executeShot (const ShotParams & sp, bool verbose = false, bool errors = false) inline
Execute given shot on the table state.
The TableState object will be modified to reflect the final state of the shot. If you need to retain the initial state, copy the object before calling. Noise is not added to the shot prior to execution.
Parameters
sp The shot parameters to execute.
verbose Print a lot of debugging information to cerr.
errors Detect internal errors (slower execution)
Exceptions
BadShotException will be thrown in case of bad parameters or errors in execution.
Definition at line 1199 of file FastFiz.h.
References Pool::getFastFizVersion(), and Pool::operator<<().
Referenced by main().
void Pool::TableState::fixOverlap (const bool VERBOSE)
Definition at line 2756 of file FastFiz.cpp.
References Pool::Utils::EPSILON, POOLFIZ_ERROR, and Pool::printOverlap().
Referenced by Pool::Shot::getDuration().
void Pool::TableState::fromStream (istream & in)
Reads a machine-readable representation of the table state from a stream.
Should be used on output of toStream() or toString().
Definition at line 2587 of file FastFiz.cpp.
References Pool::Ball::fromStream().
void Pool::TableState::fromString (const string & s)
Reads a machine-readable representation of the table state from a string.
Should be used on output of toStream() or toString().
Definition at line 2604 of file FastFiz.cpp.
References Pool::Vector::dot(), Pool::Utils::fgreater(), and Pool::Utils::fless().
Ball & Pool::TableState::getBall (Ball::Type btype)
Get ball information based on id.
If ball does not exist it will be added with unknown information. Returned ball may be modified and will affect the table state.
Definition at line 2289 of file FastFiz.cpp.
References Pool::Ball::NOTINPLAY, and Pool::Ball::UNKNOWN_ID.
Referenced by Pool::Event::copyBalls(), Pool::BallCollisionEvent::copyBalls(), Pool::StateChangeEvent::doHandle(), Pool::BallCollisionEvent::doHandle(), Pool::RailCollisionEvent::doHandle(), Pool::PocketedEvent::doHandle(), Pool::CueStrikeEvent::doHandle(), and Pool::Shot::getDuration().
const Ball & Pool::TableState::getBall (Ball::Type btype) const
Get ball information based on id.
If ball does not exist it will be added with unknown information.
Definition at line 2285 of file FastFiz.cpp.
vector<Ball>::iterator Pool::TableState::getBegin () inline
Iterator for start of ball vector.
Definition at line 1123 of file FastFiz.h.
Referenced by addNoise(), Pool::Shot::getDuration(), Pool::operator<<(), Pool::printOverlap(), and randomize().
vector<Ball>::const_iterator Pool::TableState::getBegin () const inline
Const Iterator for start of ball vector.
Definition at line 1127 of file FastFiz.h.
vector<Ball>::iterator Pool::TableState::getEnd () inline
Iterator for end of ball vector.
Definition at line 1125 of file FastFiz.h.
Referenced by addNoise(), Pool::Shot::getDuration(), Pool::operator<<(), Pool::printOverlap(), and randomize().
vector<Ball>::const_iterator Pool::TableState::getEnd () const inline
Const Iterator for end of ball vector.
Definition at line 1129 of file FastFiz.h.
Ball::Type Pool::TableState::getFirstBallHit (const ShotParams & sp)
Return the first ball hit by the cue ball while executing shot.
This function will simulate the shot up until the first ball is hit by the cue ball and then return the ball type, or UNKNOWN_ID if no ball is hit.
Definition at line 2576 of file FastFiz.cpp.
References Pool::Shot::getEventList().
int Pool::TableState::getNumBalls () const inline
Return the number of different balls used in representing this state.
Definition at line 1120 of file FastFiz.h.
const Table& Pool::TableState::getTable () const inline
Return the underlying table object.
Definition at line 1151 of file FastFiz.h.
References Pool::BadShotException::getTypeString().
Referenced by Pool::Shot::getDuration().
int Pool::TableState::isPhysicallyPossible (const ShotParams & shotParams, bool VERBOSE = false) const
Checks physical validity of the given shot parameters and table state.
Used before calling executeShot() to double-check that an error condition will not result due to invalid parameters.
Parameters
shotParams Shot parameters
VERBOSE Print debugging information
Definition at line 2355 of file FastFiz.cpp.
References Pool::ShotParams::a, Pool::ShotParams::b, Pool::Ball::CUE, Pool::Utils::fgreater(), Pool::Utils::fless(), Pool::Utils::flessequal(), Pool::Vector::norm(), Pool::ShotParams::phi, Pool::Vector::rotateRad(), Pool::ShotParams::theta, Pool::ShotParams::v, Pool::Point::x, Pool::Vector::x, Pool::Point::y, Pool::Vector::y, and Pool::Vector::z.
Referenced by Pool::Shot::getDuration(), and main().
int Pool::TableState::isValidBallPlacement (bool VERBOSE = false) const
Returns BAD_X_VAL or BAD_Y_VAL if any ball that is in play is off the table or BALL_OVERLAP if any ball is overlapping with another ball.
Used to check cue ball placement validity in the case of Ball In Hand, for example.
Parameters
VERBOSE Print debugging information
Definition at line 2300 of file FastFiz.cpp.
References Pool::Ball::dist(), Pool::Utils::fgreater(), Pool::Utils::fless(), Pool::Ball::getPos(), Pool::Ball::isInPlay(), Pool::Ball::overlaps(), Pool::Point::x, and Pool::Point::y.
Referenced by addNoise(), and Pool::Shot::getDuration().
TableState & Pool::TableState::operator= (const TableState & rhs)
Assignment operator.
Definition at line 2216 of file FastFiz.cpp.
void Pool::TableState::randomize ()
Randomly position all balls on the table.
Definition at line 2540 of file FastFiz.cpp.
References getBegin(), getEnd(), Pool::Ball::NOTINPLAY, Pool::Utils::rng(), and Pool::Ball::STATIONARY.
void Pool::TableState::setBall (Ball & b)
Modify specified ball id with specified ball information, adding if needed.
Definition at line 2237 of file FastFiz.cpp.
References Pool::Ball::getID(), Pool::Ball::getPos(), and Pool::Ball::getState().
Referenced by main().
void Pool::TableState::setBall (Ball::Type btype, Ball::State state, Point r)
Set a ball's state and position, adding if needed.
Definition at line 2224 of file FastFiz.cpp.
References Pool::Ball::UNKNOWN_ID.
void Pool::TableState::setBall (Ball::Type btype, Ball::State state, double x, double y)
Set a ball's state and position, adding if needed.
Definition at line 2241 of file FastFiz.cpp.
void Pool::TableState::spotBall (Ball::Type btype, double dither = DITHER)
Spot a pocketed ball at or near the foot spot, with dithering if needed.
Definition at line 2245 of file FastFiz.cpp.
References Pool::Ball::STATIONARY.
void Pool::TableState::toStream (ostream & out) const
Writes a machine-readable representation of the table state to a stream.
Definition at line 2580 of file FastFiz.cpp.
Referenced by Pool::Shot::getDuration(), and Pool::LogWriter::write().
string Pool::TableState::toString () const
Returns a machine-readable representation of the table state as a string.
Definition at line 2598 of file FastFiz.cpp.
Referenced by Pool::Shot::getDuration().
Member Data Documentation
const int Pool::TableState::BAD_A_VAL = 1 static
This integer is used within the bitmask integer returned by Table::isPhysicallyPossible() and Table::isValidBallPlacement() (as well as the fizG versions of those classes).
It indicates that shot parameter 'a' is invalid or not physically possible; the actual integer returned by these methods is simply the OR'ed combinations of the all the possibilities from the list under the heading 'Variables' in the HTML documentation or listed below in the header file; you can AND the result returned by these methods with any of the possibilities from the list below to test if that particular possibility is true.
Definition at line 1028 of file FastFiz.h.
const int Pool::TableState::BAD_B_VAL = 2 static
This integer is used within the bitmask integer returned by Table::isPhysicallyPossible() and Table::isValidBallPlacement() (as well as the fizG versions of those classes).
It indicates that shot parameter 'b' is invalid or not physically possible; the actual integer returned by these methods is simply the OR'ed combinations of the all the possibilities from the list under the heading 'Variables' in the HTML documentation or listed below in the header file; you can AND the result returned by these methods with any of the possibilities from the list below to test if that particular possibility is true.
Definition at line 1038 of file FastFiz.h.
const int Pool::TableState::BAD_PHI_VAL = 8 static
This integer is used within the bitmask integer returned by Table::isPhysicallyPossible() and Table::isValidBallPlacement() (as well as the fizG versions of those classes).
It indicates that shot parameter 'phi' is invalid or not physically possible; the actual integer returned by these methods is simply the OR'ed combinations of the all the possibilities from the list under the heading 'Variables' in the HTML documentation or listed below in the header file; you can AND the result returned by these methods with any of the possibilities from the list below to test if that particular possibility is true.
Definition at line 1058 of file FastFiz.h.
const int Pool::TableState::BAD_THETA_VAL = 4 static
This integer is used within the bitmask integer returned by Table::isPhysicallyPossible() and Table::isValidBallPlacement() (as well as the fizG versions of those classes).
It indicates that shot parameter 'theta' is invalid or not physically possible; the actual integer returned by these methods is simply the OR'ed combinations of the all the possibilities from the list under the heading 'Variables' in the HTML documentation or listed below in the header file; you can AND the result returned by these methods with any of the possibilities from the list below to test if that particular possibility is true.
Definition at line 1048 of file FastFiz.h.
const int Pool::TableState::BAD_V_VAL = 16 static
This integer is used within the bitmask integer returned by Table::isPhysicallyPossible() and Table::isValidBallPlacement() (as well as the fizG versions of those classes).
It indicates that shot parameter 'V' is invalid or not physically possible; the actual integer returned by these methods is simply the OR'ed combinations of the all the possibilities from the list under the heading 'Variables' in the HTML documentation or listed below in the header file; you can AND the result returned by these methods with any of the possibilities from the list below to test if that particular possibility is true.
Definition at line 1068 of file FastFiz.h.
const int Pool::TableState::BAD_X_VAL = 32 static
This integer is used within the bitmask integer returned by Table::isPhysicallyPossible() and Table::isValidBallPlacement() (as well as the fizG versions of those classes).
It indicates that the cue ball placement x-coordinate is out of range; the actual integer returned by these methods is simply the OR'ed combinations of the all the possibilities from the list under the heading 'Variables' in the HTML documentation or listed below in the header file; you can AND the result returned by these methods with any of the possibilities from the list below to test if that particular possibility is true.
Definition at line 1078 of file FastFiz.h.
const int Pool::TableState::BAD_Y_VAL = 64 static
This integer is used within the bitmask integer returned by Table::isPhysicallyPossible() and Table::isValidBallPlacement() (as well as the fizG versions of those classes).
It indicates that the cue ball placement y-coordinate is out of range; the actual integer returned by these methods is simply the OR'ed combinations of the all the possibilities from the list under the heading 'Variables' in the HTML documentation or listed below in the header file; you can AND the result returned by these methods with any of the possibilities from the list below to test if that particular possibility is true.
Definition at line 1088 of file FastFiz.h.
const int Pool::TableState::BALL_OVERLAP = 256 static
This integer is used within the bitmask integer returned by Table::isPhysicallyPossible() and Table::isValidBallPlacement() (as well as the fizG versions of those classes).
It indicates that the ball placement x-y coordinates result in an overlap with another ball on table; the actual integer returned by these methods is simply the OR'ed combinations of the all the possibilities from the list under the heading 'Variables' in the HTML documentation or listed below in the header file; you can AND the result returned by these methods with any of the possibilities from the list below to test if that particular possibility is true.
Definition at line 1108 of file FastFiz.h.
const int Pool::TableState::CUE_STICK_COLLISION = 128 static
This integer is used within the bitmask integer returned by Table::isPhysicallyPossible() and Table::isValidBallPlacement() (as well as the fizG versions of those classes).
It indicates that the cue will collide with a ball before striking the cue ball; the actual integer returned by these methods is simply the OR'ed combinations of the all the possibilities from the list under the heading 'Variables' in the HTML documentation or listed below in the header file; you can AND the result returned by these methods with any of the possibilities from the list below to test if that particular possibility is true.
Definition at line 1098 of file FastFiz.h.
const double Pool::TableState::MAX_THETA = 70.0 static
maximum theta allowed [degrees]
Definition at line 1009 of file FastFiz.h.
const double Pool::TableState::MAX_VELOCITY = 10 static
maximum velocity allowed [m/s]
Definition at line 1007 of file FastFiz.h.
const double Pool::TableState::MIN_THETA = 0.0 static
minimum theta allowed [degrees]
Definition at line 1008 of file FastFiz.h.
const int Pool::TableState::OK_PRECONDITION = 0 static
This integer is used within the bitmask integer returned by Table::isPhysicallyPossible() and Table::isValidBallPlacement() (as well as the fizG versions of those classes).
It indicates that all shot parameters are valid; the actual integer returned by these methods is simply the OR'ed combinations of the all the possibilities from the list under the heading 'Variables' in the HTML documentation or listed below in the header file; you can AND the result returned by these methods with any of the possibilities from the list below to test if that particular possibility is true.
Definition at line 1018 of file FastFiz.h.
Referenced by Pool::Shot::getDuration(), and main().
The documentation for this class was generated from the following files:
FastFiz.h
FastFiz.cpp