FastFiz: Pool::AIBase Class Reference
Pool::AIBase Class Reference abstract
Base class for pool AI implementations.
#include <AIBase.h>
Public Member Functions
AIBase (libconfig::Config &config, Stopwatch *stopwatch)
Constructor.
virtual GameShot & computeShot (const GameState &gs, const Pool::Noise *const noise=NULL)
Compute a shot for a given game state and noise information.
virtual GameShot & reComputeShot ()
Recompute a shot.
virtual string getName () const
Return the name of your AI.
virtual string getPassword () const
Return the password for your AI.
virtual string getOwner () const
Return the owner ID for the AI.
virtual bool forGame (GameType gt)
Check if the AI can handle a specific game type.
Protected Member Functions
virtual Decision decide ()
Make a decision when a decision node is reached.
virtual void shoot ()
Make a shot when one is needed.
virtual void breakShot ()=0
Make a break shot.
virtual void otherShot ()=0
Make a non-break shot.
Protected Attributes
libconfig::Config & _config
Configuration information for the agent.
Stopwatch *const _stopwatch
Stopwatch object defining time model used by the agent.
const GameState * gameState
State of the game when AI is needed.
const Noise * noise
Noise information.
GameShot shot
Shot computed by AI.
int retries
Number of attempts remaining for an illegal/impossible shot.
Detailed Description
Base class for pool AI implementations.
When writing your AI, inherit from this class.
Definition at line 28 of file AIBase.h.
Constructor & Destructor Documentation
Pool::AIBase::AIBase (libconfig::Config & config, Stopwatch * stopwatch) inline
Constructor.
Generates a new AI instance.
Parameters
config Config object with configuration information for the AI.
stopwatch A Stopwatch object allowing access to the time model used.
Definition at line 35 of file AIBase.h.
Member Function Documentation
virtual void Pool::AIBase::breakShot () protected pure virtual
Make a break shot.
This is a pure virtual function that must be re-implemented by any AI. The game state and noise information are stored in class members. Resulting shot should be written to the "shot" member.
GameShot & Pool::AIBase::computeShot (const GameState & gs, const Pool::Noise *const noise = NULL) virtual
Compute a shot for a given game state and noise information.
Default implementation keeps shot information, makes sure the AI can handle the game type, and then calls decide() or shoot() based on the turn type.
Generally, you need not re-implement this method in your AI.
Definition at line 6 of file AIBase.cpp.
References Pool::DEC_CONCEDE, Pool::DEC_NO_DECISION, Pool::GameState::decisionAllowed(), Pool::GameState::gameType(), Pool::GameState::isTerminal(), MAX_RETRIES, Pool::GameState::shotRequired(), Pool::Ball::UNKNOWN_ID, and Pool::Table::UNKNOWN_POCKET.
Decision Pool::AIBase::decide () protected virtual
Make a decision when a decision node is reached.
State and noise information is stored in class memebers. Default implementation is to rerack whenever an eight-ball decision is needeed.
AI authors should re-implement this method if any other decision is desired.
Definition at line 41 of file AIBase.cpp.
References Pool::DEC_CONCEDE, Pool::DEC_RERACK, Pool::TT_EIGHTBALL_8BALL_POCKETED_ON_BREAK, and Pool::TT_EIGHTBALL_FOUL_ON_BREAK.
virtual bool Pool::AIBase::forGame (GameType gt) inline virtual
Check if the AI can handle a specific game type.
Default implementation is to always return false.
AI authors should re-impelment this method to return true for game types that are supported by the AI.
Definition at line 79 of file AIBase.h.
virtual string Pool::AIBase::getName () const inline virtual
Return the name of your AI.
Default implementation reads it from the config file under "name".
Generally, you need not re-implement this method in your AI.
Definition at line 57 of file AIBase.h.
virtual string Pool::AIBase::getOwner () const inline virtual
Return the owner ID for the AI.
Owner ID is used in a multi-user server to allow non-admin users to view information related to the agent. Default implementation does not specify an owner ID.
Generally, you need not re-implement this method in your AI.
Definition at line 72 of file AIBase.h.
virtual string Pool::AIBase::getPassword () const inline virtual
Return the password for your AI.
Default implementation reads it from the config file under "password".
Generally, you need not re-implement this method in your AI.
Definition at line 64 of file AIBase.h.
virtual void Pool::AIBase::otherShot () protected pure virtual
Make a non-break shot.
This includes ball-in-hand shots. This is a pure virtual function that must be re-implemented by any AI. The game state and noise information are stored in class members. Resulting shot should be written to the "shot" member.
GameShot & Pool::AIBase::reComputeShot () virtual
Recompute a shot.
Called after a shot sent by the AI was deemed physcially impossible or underspecified. Default implementation retries previous shot again up to MAX_RETRIES times, then concedes the game.
Generally, you need not re-implement this method in your AI.
Definition at line 31 of file AIBase.cpp.
References Pool::DEC_CONCEDE, and Pool::GameShot::decision.
void Pool::AIBase::shoot () protected virtual
Make a shot when one is needed.
The game state and noise information are stored in class members. Resulting shot should be written to the "shot" member. Default implementation calls breakShot() or otherShot() depending on the turn type.
Generally, you need not re-implement this method in your AI.
Definition at line 52 of file AIBase.cpp.
References Pool::TT_BREAK.
Member Data Documentation
libconfig::Config& Pool::AIBase::_config protected
Configuration information for the agent.
Definition at line 108 of file AIBase.h.
Stopwatch* const Pool::AIBase::_stopwatch protected
Stopwatch object defining time model used by the agent.
Definition at line 111 of file AIBase.h.
const GameState* Pool::AIBase::gameState protected
State of the game when AI is needed.
Definition at line 114 of file AIBase.h.
const Noise* Pool::AIBase::noise protected
Noise information.
Definition at line 117 of file AIBase.h.
int Pool::AIBase::retries protected
Number of attempts remaining for an illegal/impossible shot.
Definition at line 123 of file AIBase.h.
GameShot Pool::AIBase::shot protected
Shot computed by AI.
Definition at line 120 of file AIBase.h.
The documentation for this class was generated from the following files:
AIBase.h
AIBase.cpp