FastFiz: Pool::BallCollisionEvent Class Reference
Pool::BallCollisionEvent Class Reference
An event involving two balls colliding.
#include <FastFiz.h>
Public Member Functions
BallCollisionEvent (double time, Ball::Type b1, Ball::Type b2)
virtual Type getType () const
Returns the type of the event.
virtual string getTypeString () const
Returns the type of the event as a string.
virtual bool relatedTo (const Event &other) const
Returns true if this event and the other event affect a shared ball.
virtual bool involvesBall (Ball::Type b) const
Returns true if this event affects specified ball.
virtual ~BallCollisionEvent ()
virtual Ball::Type getBall2 () const
Returns the id of the second ball involved in the event, if applicable.
virtual Ball & getBall2Data ()
Returns the physical information (location, velocity,spin) of the second ball involved in the event.
Public Member Functions inherited from Pool::Event
Event (double time, Ball::Type b)
Create a new base event.
double getTime () const
Returns the event's simulation time index.
Ball::Type getBall1 () const
Returns the id of first (possibly only) ball involved in the event.
Ball & getBall1Data ()
Returns the physical information (location, velocity,spin) of the first (possibly only) ball involved in the event.
bool operator< (const Event &other) const
Sorts Events by time.
string toString () const
Returns a human-readble string representation of the event.
virtual ~Event ()
Destructor.
void handle (TableState &ts, bool VERBOSE=false)
Used within physics code to apply event to a table state, modifying ball states, positions, and properties Also updates ball information within event.
Protected Member Functions
virtual void copyBalls (TableState &ts)
virtual void doHandle (TableState &ts, bool VERBOSE) const
virtual ostream & dump (ostream &out) const
Protected Attributes
Ball::Type _ball2
Ball * _ball2Data
Protected Attributes inherited from Pool::Event
double _time
Ball::Type _ball1
Ball * _ball1Data
Additional Inherited Members
Public Types inherited from Pool::Event
enum Type {
NO_EVENT, STATE_CHANGE, BALL_COLLISION, RAIL_COLLISION,
POCKETED, CUE_STRIKE, MISCUE, UNKNOWN_EVENT
}
Indicates the type of event.
Static Public Member Functions inherited from Pool::Event
static bool eventCmp (const Event *event1, const Event *event2)
Event comparison function, calls operator<.
Detailed Description
An event involving two balls colliding.
This is the only event where Ball2 is defined.
Definition at line 809 of file FastFiz.h.
Constructor & Destructor Documentation
Pool::BallCollisionEvent::BallCollisionEvent (double time, Ball::Type b1, Ball::Type b2) inline
Definition at line 811 of file FastFiz.h.
virtual Pool::BallCollisionEvent::~BallCollisionEvent () inline virtual
Definition at line 817 of file FastFiz.h.
Member Function Documentation
void Pool::BallCollisionEvent::copyBalls (TableState & ts) protected virtual
Reimplemented from Pool::Event.
Definition at line 899 of file FastFiz.cpp.
References Pool::Event::copyBalls(), and Pool::TableState::getBall().
void Pool::BallCollisionEvent::doHandle (TableState & ts, bool VERBOSE) const protected virtual
Implements Pool::Event.
Definition at line 695 of file FastFiz.cpp.
References Pool::Utils::angle(), Pool::Vector::cross(), Pool::Utils::DEGREES, Pool::TableState::getBall(), Pool::Ball::getIDString(), Pool::Ball::getPos(), Pool::Ball::getRadius(), Pool::Ball::getSpin(), Pool::Ball::getState(), Pool::Ball::getVelocity(), Pool::Vector::mag(), Pool::Vector::rotateDeg(), Pool::Ball::setSpin(), Pool::Ball::setVelocity(), Pool::Ball::SPINNING, Pool::Utils::START_ZERO, Pool::Ball::STATIONARY, Pool::Ball::updateState(), Pool::Utils::vzero(), Pool::Vector::x, Pool::Vector::y, and Pool::Vector::z.
ostream & Pool::BallCollisionEvent::dump (ostream & out) const protected virtual
Reimplemented from Pool::Event.
Definition at line 929 of file FastFiz.cpp.
References Pool::Event::dump(), and Pool::Ball::getIDString().
virtual Ball::Type Pool::BallCollisionEvent::getBall2 () const inline virtual
Returns the id of the second ball involved in the event, if applicable.
Reimplemented from Pool::Event.
Definition at line 819 of file FastFiz.h.
virtual Ball& Pool::BallCollisionEvent::getBall2Data () inline virtual
Returns the physical information (location, velocity,spin) of the second ball involved in the event.
If no second ball is involved, will return the first ball information. May cause a null pointer exception if the information is not available (if event was not yet handled).
Reimplemented from Pool::Event.
Definition at line 820 of file FastFiz.h.
virtual Type Pool::BallCollisionEvent::getType () const inline virtual
Returns the type of the event.
Reimplemented from Pool::Event.
Definition at line 813 of file FastFiz.h.
virtual string Pool::BallCollisionEvent::getTypeString () const inline virtual
Returns the type of the event as a string.
Reimplemented from Pool::Event.
Definition at line 814 of file FastFiz.h.
bool Pool::BallCollisionEvent::involvesBall (Ball::Type b) const virtual
Returns true if this event affects specified ball.
Reimplemented from Pool::Event.
Definition at line 687 of file FastFiz.cpp.
bool Pool::BallCollisionEvent::relatedTo (const Event & other) const virtual
Returns true if this event and the other event affect a shared ball.
Reimplemented from Pool::Event.
Definition at line 683 of file FastFiz.cpp.
References Pool::Event::involvesBall().
Member Data Documentation
Ball::Type Pool::BallCollisionEvent::_ball2 protected
Definition at line 822 of file FastFiz.h.
Ball* Pool::BallCollisionEvent::_ball2Data protected
Definition at line 823 of file FastFiz.h.
The documentation for this class was generated from the following files:
FastFiz.h
FastFiz.cpp