FastFiz: Pool::EightBallState Class Reference
Pool::EightBallState Class Reference
Implementation of the rules of Eight-Ball.
#include <Rules.h>
Public Member Functions
EightBallState (double timeleft=0.0, double timeleft_opp=0.0)
Create new (racked) Eight Ball state.
EightBallState (string gameString)
Construct an EightBallState by reading from string.
GameType gameType () const
Returns the type of game (GT_EIGHTBALL)
EightBallState (istream &is)
Construct an EightBallState by reading from stream.
virtual void toStream (ostream &out) const
Exports the GameState to a stream.
virtual GameState * clone ()
Allocate a new copy of this GameState.
virtual const bool playingSolids () const
Returns true if current player should shoot solids.
virtual const bool isOpenTable () const
Returns true if solids/stripes have not been determined yet.
virtual bool shotRequired () const
Determines if the agent is required to provide a valid shot.
Public Member Functions inherited from Pool::GameState
GameState (double timeleft=0.0, double timeleft_opp=0.0)
Create new game state.
GameState (string gameString)
Parse common part of GameState from string.
virtual bool isTerminal () const
Determines if the GameState is in a terminal state (i.e.
virtual bool positionRequired () const
Determines if the agent must provide a valid position for the cue ball.
virtual bool decisionAllowed () const
Determines if the agent is allowed to make a decision.
virtual string toString ()
Serializes the GameState as a string.
virtual const TurnType getTurnType () const
virtual const bool curPlayerStarted () const
Returns true if the current player had the inital break.
virtual const double timeLeft () const
Returns the amount of time left (in seconds) for the current player.
virtual const double timeLeftOpp () const
Returns the amount of time left (in seconds) for the other player.
virtual const TableState & tableState () const
Allows caller read-only access to the internal table state.
virtual ShotResult executeShot (const GameShot &shot, Shot **shotObj=NULL)
Calls the rules to check the shot values, executes the shot using the physics library, and then evalues the resulting GameState.
Protected Member Functions
virtual void importFromStream (istream &sourceStream)
Read common information from an input stream.
virtual bool isLegalTurnType () const
Returns true if the current turnType is defined for the current game.
virtual PreProcessCode preProcess (const GameShot &shot)
Pre-evaluate shot parameters for the current game state.
virtual void processShot (const vector< Event * > &eventList, const GameShot &gameShot)
Called after shot execution to process an event list and adjust game state.
virtual void rack ()
Update TableState to the racked state, does NOT update other params.
virtual void switchSides ()
Utility function to switch the active player.
Protected Attributes
bool _openTable
bool _solids
Protected Attributes inherited from Pool::GameState
TableState _tableState
TurnType _turnType
double _timeLeft
double _timeLeftOpp
bool _curPlayerStarted
bool _switchedSides
Friends
ostream & operator<< (ostream &os, const EightBallState &obj)
Convienence functions to facilitate working with the strings used to send over the wire.
istream & operator>> (istream &is, EightBallState &obj)
See above.
Additional Inherited Members
Static Public Member Functions inherited from Pool::GameState
static GameState * Factory (istream &sourceStream)
Generate a new GameState object by reading information from an input stream.
static GameState * Factory (string sourceString)
Generate a new GameState object by reading information from an input string.
static GameState * RackedState (GameType gameType)
Returns a newly allocated racked (initial) state of a game by game type.
Protected Types inherited from Pool::GameState
enum PreProcessCode { PPC_BADPARAMS =0, PPC_G_NOEXECUTE, PPC_G_NORMAL, PPC_G_PLACECUE }
Possible results of pre-evaluation of shot parameters for current game state.
Detailed Description
Implementation of the rules of Eight-Ball.
Definition at line 295 of file Rules.h.
Constructor & Destructor Documentation
Pool::EightBallState::EightBallState (double timeleft = 0.0, double timeleft_opp = 0.0) inline explicit
Create new (racked) Eight Ball state.
Definition at line 300 of file Rules.h.
References Pool::operator<<(), Pool::operator>>(), and Pool::rack().
Pool::EightBallState::EightBallState (string gameString) inline
Construct an EightBallState by reading from string.
Used by Factory.
Definition at line 321 of file Rules.h.
Pool::EightBallState::EightBallState (istream & is) inline
Construct an EightBallState by reading from stream.
Used by Factory.
Definition at line 337 of file Rules.h.
Member Function Documentation
GameState * EightBallState::clone () virtual
Allocate a new copy of this GameState.
Implements Pool::GameState.
Definition at line 547 of file Rules.cpp.
GameType Pool::EightBallState::gameType () const inline virtual
Returns the type of game (GT_EIGHTBALL)
Implements Pool::GameState.
Definition at line 331 of file Rules.h.
References Pool::GT_EIGHTBALL.
void EightBallState::importFromStream (istream & sourceStream) protected virtual
Read common information from an input stream.
Reimplemented from Pool::GameState.
Definition at line 178 of file Rules.cpp.
References importFromStream(), and Pool::operator>>().
Referenced by importFromStream().
virtual bool Pool::EightBallState::isLegalTurnType () const inline protected virtual
Returns true if the current turnType is defined for the current game.
Reimplemented from Pool::GameState.
Definition at line 362 of file Rules.h.
References Pool::GameState::isLegalTurnType(), Pool::rack(), Pool::TT_EIGHTBALL_8BALL_POCKETED_ON_BREAK, and Pool::TT_EIGHTBALL_FOUL_ON_BREAK.
virtual const bool Pool::EightBallState::isOpenTable () const inline virtual
Returns true if solids/stripes have not been determined yet.
Reimplemented from Pool::GameState.
Definition at line 349 of file Rules.h.
virtual const bool Pool::EightBallState::playingSolids () const inline virtual
Returns true if current player should shoot solids.
Only meaningful if isOpenTable is false.
Reimplemented from Pool::GameState.
Definition at line 348 of file Rules.h.
GameState::PreProcessCode EightBallState::preProcess (const GameShot & shot) protected virtual
Pre-evaluate shot parameters for the current game state.
Implements Pool::GameState.
Definition at line 200 of file Rules.cpp.
References Pool::GameShot::ball, Pool::GameShot::cue_y, Pool::DEC_CONCEDE, Pool::DEC_EIGHTBALL_RERACK_OPP_SHOOT, Pool::DEC_KEEP_SHOOTING, Pool::DEC_RERACK, Pool::GameShot::decision, Pool::GameShot::pocket, Pool::rack(), Pool::TT_BALL_IN_HAND, Pool::TT_BEHIND_LINE, Pool::TT_BREAK, Pool::TT_EIGHTBALL_8BALL_POCKETED_ON_BREAK, Pool::TT_EIGHTBALL_FOUL_ON_BREAK, Pool::TT_NORMAL, and Pool::TT_WIN.
void EightBallState::processShot (const vector< Event * > & eventList, const GameShot & gameShot) protected virtual
Called after shot execution to process an event list and adjust game state.
Implements Pool::GameState.
Definition at line 274 of file Rules.cpp.
References Pool::GameShot::ball, Pool::PocketedEvent::getPocket(), Pool::Ball::getPos(), Pool::GameShot::pocket, Pool::TT_BALL_IN_HAND, Pool::TT_BEHIND_LINE, Pool::TT_BREAK, Pool::TT_EIGHTBALL_8BALL_POCKETED_ON_BREAK, Pool::TT_EIGHTBALL_FOUL_ON_BREAK, Pool::TT_NORMAL, Pool::TT_WIN, and Pool::Point::y.
void EightBallState::rack () protected virtual
Update TableState to the racked state, does NOT update other params.
Implements Pool::GameState.
Definition at line 499 of file Rules.cpp.
References Pool::Table::getFootSpot(), Pool::Table::getHeadString(), Pool::Table::getWidth(), Pool::Point::x, and Pool::Point::y.
virtual bool Pool::EightBallState::shotRequired () const inline virtual
Determines if the agent is required to provide a valid shot.
Reimplemented from Pool::GameState.
Definition at line 351 of file Rules.h.
References Pool::GameState::shotRequired(), Pool::TT_EIGHTBALL_8BALL_POCKETED_ON_BREAK, and Pool::TT_EIGHTBALL_FOUL_ON_BREAK.
void EightBallState::switchSides () protected virtual
Utility function to switch the active player.
Reimplemented from Pool::GameState.
Definition at line 194 of file Rules.cpp.
void EightBallState::toStream (ostream & out) const virtual
Exports the GameState to a stream.
Reimplemented from Pool::GameState.
Definition at line 540 of file Rules.cpp.
Friends And Related Function Documentation
ostream& operator<< (ostream & os, const EightBallState & obj) friend
Convienence functions to facilitate working with the strings used to send over the wire.
istream& operator>> (istream & is, EightBallState & obj) friend
See above.
Member Data Documentation
bool Pool::EightBallState::_openTable protected
Definition at line 388 of file Rules.h.
bool Pool::EightBallState::_solids protected
Definition at line 388 of file Rules.h.
The documentation for this class was generated from the following files:
Rules.h
Rules.cpp