FastFiz: Stopwatch Class Reference
Stopwatch Class Reference abstract
Utility class heirarchy to measure time in various ways.
#include <Stopwatch.h>
Public Member Functions
Stopwatch ()
Create a new stopwatch.
void clear ()
Reset stopwatch to zero and stop.
void restart ()
Reset stopwatch to zero and start.
double getElapsed () const
Get current reading on stopwatch.
void stop ()
Stop the stopwatch.
void start ()
Start the stopwatch.
virtual Stopwatch * create () const =0
Create a new stopwatch of same type (factory).
Protected Member Functions
virtual double now () const =0
Get the current time in stopwatch units.
Detailed Description
Utility class heirarchy to measure time in various ways.
Base class implements general time handling with arbitrary units. The virtual now() method should be implemented in subclasses.
Definition at line 17 of file Stopwatch.h.
Constructor & Destructor Documentation
Stopwatch::Stopwatch () inline
Create a new stopwatch.
Not running.
Definition at line 21 of file Stopwatch.h.
Member Function Documentation
void Stopwatch::clear () inline
Reset stopwatch to zero and stop.
Definition at line 23 of file Stopwatch.h.
virtual Stopwatch* Stopwatch::create () const pure virtual
Create a new stopwatch of same type (factory).
Implemented in VirtualStopwatch2, VirtualStopwatch, CPUStopwatch, and RealTimeStopwatch.
Referenced by start().
double Stopwatch::getElapsed () const inline
Get current reading on stopwatch.
Definition at line 27 of file Stopwatch.h.
References now().
virtual double Stopwatch::now () const protected pure virtual
Get the current time in stopwatch units.
Implemented in VirtualStopwatch2, VirtualStopwatch, and TimevalStopwatch.
Referenced by getElapsed(), restart(), start(), and stop().
void Stopwatch::restart () inline
Reset stopwatch to zero and start.
Definition at line 25 of file Stopwatch.h.
References now().
void Stopwatch::start () inline
Start the stopwatch.
Retain time reading.
Definition at line 31 of file Stopwatch.h.
References create(), and now().
void Stopwatch::stop () inline
Stop the stopwatch.
Retain time reading.
Definition at line 29 of file Stopwatch.h.
References now().
The documentation for this class was generated from the following file:
Stopwatch.h