FastFiz: Pool Namespace Reference
Pool Namespace Reference
The namespace in which all of the physics and rules components for FastFiz reside.
Classes
class AIBase
Base class for pool AI implementations.
class BadShotException
The exception thrown when a Shot cannot be completed.
class Ball
This class represents the state and position of a single pool ball.
class BallCollisionEvent
An event involving two balls colliding.
class CueStrikeEvent
The initial event in any shot – cue ball struck by the cue stick.
class EightBallState
Implementation of the rules of Eight-Ball.
class Event
Base class of the Event heirarchy.
struct GameShot
The object that holds all parameters necessary for a complete shot.
class GameState
This defines most of the information and functions necessary about the state of a game.
class GaussianNoise
Class implementing Gaussian noise.
class LogWriter
Output game/table states and shots to a stream in a text-based format supported by web-based game viewer.
class NineBallState
Implementation of the rules of Nine-Ball.
class Noise
Base Noise class for implementing a generic type of noise.
class NoNoise
Trivial class implementing null noise.
class PocketedEvent
An event involving a ball entering a pocket.
struct Point
A two-dimensional Point class.
class RailCollisionEvent
An event involving a ball colliding with a rail.
class Shot
Detailed result of a simulation of a shot.
struct ShotParams
A struct of the parameters for a CUE_STRIKE.
class StateChangeEvent
An event invloving a physical transition of state, e.g between SLIDING and ROLLING.
class Table
Class representing physical properties of a pool table.
class TableState
The physical state of balls on a table.
class Utils
General utility functions.
struct Vector
A three-dimensional Vector class.
Enumerations
enum NoiseType { NT_UNDEFINED, NT_NONE, NT_GAUSSIAN =2 }
Noise Types.
enum Decision {
DEC_NO_DECISION, DEC_KEEP_SHOOTING, DEC_RERACK, DEC_EIGHTBALL_RERACK_OPP_SHOOT,
DEC_CONCEDE, DEC_NINEBALL_PUSH_OUT
}
A definition of all the possible decisions a client can make.
enum TurnType {
TT_NORMAL, TT_BALL_IN_HAND, TT_BEHIND_LINE, TT_RESERVED,
TT_BREAK, TT_WIN, TT_EIGHTBALL_FOUL_ON_BREAK, TT_EIGHTBALL_8BALL_POCKETED_ON_BREAK,
TT_NINEBALL_FIRST_SHOT, TT_NINEBALL_PUSH_OUT
}
An enumeration of all the possible turn types an agent might have to deal with.
enum GameType {
GT_NONE, GT_EIGHTBALL, GT_NINEBALL, GT_SNOOKER,
GT_ONEPOCKET
}
An enumeration of all the game types.
enum ShotResult {
SR_OK, SR_OK_LOST_TURN, SR_BAD_PARAMS, SR_SHOT_IMPOSSIBLE,
SR_TIMEOUT
}
The set of all possible results of an execution of a shot.
Functions
ostream & operator<< (ostream &out, const ShotParams &rhs)
Writes human-readable output for the ShotParams object to the output stream.
ostream & operator<< (ostream &out, const Point &rhs)
Writes human-readable output for the Point object to the output stream.
ostream & operator<< (ostream &out, const Vector &rhs)
ostream & operator<< (ostream &out, const Ball &rhs)
ostream & operator<< (ostream &out, const Event &rhs)
ostream & operator<< (ostream &out, Shot &rhs)
Print a human-readable representation of the shot to a stream.
ostream & operator<< (ostream &out, TableState &rhs)
string getFastFizVersion ()
Return a string identifying the version and build information of the library.
void rack (TableState &ts)
Rack table state for Eight-ball.
void printEvents (list< Event * > events)
Dump event list to standard error.
void printOverlap (TableState &ts)
Print overlapping balls in table state.
TableState * getTestState ()
Return a racked state for testing purposes.
ShotParams * getTestShotParams ()
Return sample shot parameters that work with the test state.
string getPoolfizVersion ()
Return a string identifying the version and build information of the library.
istream & operator>> (istream &is, NoiseType nt)
ostream & operator<< (ostream &os, const Noise &obj)
string getRulesVersion ()
istream & operator>> (istream &is, TurnType &tt)
Detailed Description
The namespace in which all of the physics and rules components for FastFiz reside.
Enumeration Type Documentation
enum Pool::Decision
A definition of all the possible decisions a client can make.
If a state does not require a decision, but rather only a shot, set the decision of a GameShot to DEC_NO_DECISION. Otherwise, use the appropriate decision.
Enumerator
DEC_NO_DECISION
Default decision when none is needed.
DEC_KEEP_SHOOTING
Keep your turn after opponent's bad break or push out.
DEC_RERACK
Re-rack the balls and get a turn after opponent's bad break.
DEC_EIGHTBALL_RERACK_OPP_SHOOT
If TT_EIGHTBALL_FOUL_ON_BREAK, the incoming player can decide to re-rack and have the opponent (original breaker) re-break.
If they wimply want to re-rack and themselves shoot, choose DEC_RERACK
DEC_CONCEDE
concede the game, always allowed
DEC_NINEBALL_PUSH_OUT
In TT_NINEBALL_FIRST_SHOT, means declaring "Push Out".
In TT_NINEBALL_PUSH_OUT means player does not accept position.
Definition at line 22 of file Rules.h.
enum Pool::GameType
An enumeration of all the game types.
Only Eight-Ball is supported.
Enumerator
GT_NONE
GT_EIGHTBALL
GT_NINEBALL
GT_SNOOKER
GT_ONEPOCKET
Definition at line 62 of file Rules.h.
enum Pool::NoiseType
Noise Types.
Enumerator
NT_UNDEFINED
NT_NONE
NT_GAUSSIAN
Definition at line 19 of file Noise.h.
enum Pool::ShotResult
The set of all possible results of an execution of a shot.
Enumerator
SR_OK
The shot was executed, and the shooter won the game or may shoot again.
SR_OK_LOST_TURN
The shot was executed, but the shooter has lost their turn, and possibly the game.
SR_BAD_PARAMS
The shot information given is not applicable to the game state.
SR_SHOT_IMPOSSIBLE
The shot is not physically possible.
For example, if a ball is in the way of the cue stick.
SR_TIMEOUT
The agent took too much time computing the shot, and timed out.
Shot was not executed.
Definition at line 69 of file Rules.h.
enum Pool::TurnType
An enumeration of all the possible turn types an agent might have to deal with.
The turn types are as general as possible, with a few additions as required by each specific game.
Enumerator
TT_NORMAL
Standard shot, cue ball must not be placed.
TT_BALL_IN_HAND
Cue ball must be placed anywhere on the table.
TT_BEHIND_LINE
Cue ball must be placed behind the headstring.
TT_RESERVED
Not used.
TT_BREAK
Break shot.
Cue ball must be placed behind the headstring.
TT_WIN
Current player wins.
This is a terminal state.
TT_EIGHTBALL_FOUL_ON_BREAK
If there is a foul on the break.
Needs a decision
TT_EIGHTBALL_8BALL_POCKETED_ON_BREAK
If the eight-ball is pocketed on the break.
Needs a decision
TT_NINEBALL_FIRST_SHOT
First shot after a legal break in nine-ball.
TT_NINEBALL_PUSH_OUT
Incoming player's decision node after Push Out (neesds to decide DEC_KEEP_SHOOTING or DEC_NINEBALL_PUSH_OUT)
Definition at line 37 of file Rules.h.
Function Documentation
string Pool::getFastFizVersion ()
Return a string identifying the version and build information of the library.
Definition at line 2627 of file FastFiz.cpp.
Referenced by Pool::TableState::executeShot(), and getPoolfizVersion().
string Pool::getPoolfizVersion () inline
Return a string identifying the version and build information of the library.
Deprecated:
Use getFastFizVersion().
Definition at line 1255 of file FastFiz.h.
References getFastFizVersion(), getTestShotParams(), getTestState(), printEvents(), printOverlap(), and rack().
string Pool::getRulesVersion ()
Definition at line 535 of file Rules.cpp.
ShotParams * Pool::getTestShotParams ()
Return sample shot parameters that work with the test state.
Definition at line 2729 of file FastFiz.cpp.
Referenced by getPoolfizVersion().
TableState * Pool::getTestState ()
Return a racked state for testing purposes.
Debugging function.
Definition at line 2723 of file FastFiz.cpp.
References rack().
Referenced by getPoolfizVersion().
ostream & Pool::operator<< (ostream & os, const Noise & obj)
Definition at line 92 of file Noise.cpp.
References Pool::Noise::toStream().
Referenced by Pool::Noise::Factory(), and Pool::Noise::importFromStream().
ostream & Pool::operator<< (ostream & out, const ShotParams & rhs)
Writes human-readable output for the ShotParams object to the output stream.
Definition at line 134 of file FastFiz.cpp.
References Pool::ShotParams::a, Pool::ShotParams::b, Pool::ShotParams::phi, Pool::ShotParams::theta, and Pool::ShotParams::v.
Referenced by Pool::EightBallState::EightBallState(), Pool::TableState::executeShot(), Pool::Shot::getEventList(), Pool::Ball::isPocketed(), Pool::NineBallState::NineBallState(), Pool::Point::Point(), Pool::GameState::RackedState(), Pool::ShotParams::ShotParams(), Pool::GameState::shotRequired(), and Pool::Vector::Vector().
ostream & Pool::operator<< (ostream & out, const Point & rhs)
Writes human-readable output for the Point object to the output stream.
Definition at line 143 of file FastFiz.cpp.
References Pool::Point::x, and Pool::Point::y.
ostream & Pool::operator<< (ostream & out, const Vector & rhs)
Definition at line 184 of file FastFiz.cpp.
References Pool::Vector::x, Pool::Vector::y, and Pool::Vector::z.
ostream & Pool::operator<< (ostream & out, const Ball & rhs)
Definition at line 266 of file FastFiz.cpp.
References Pool::Ball::getIDString(), Pool::Ball::getPos(), Pool::Ball::getSpin(), Pool::Ball::getStateString(), and Pool::Ball::getVelocity().
ostream& Pool::operator<< (ostream & out, const Event & rhs)
Definition at line 911 of file FastFiz.cpp.
References Pool::Event::dump().
ostream & Pool::operator<< (ostream & out, Shot & rhs)
Print a human-readable representation of the shot to a stream.
Definition at line 959 of file FastFiz.cpp.
References Pool::Shot::getEventList().
ostream & Pool::operator<< (ostream & out, TableState & rhs)
Definition at line 2207 of file FastFiz.cpp.
References Pool::TableState::getBegin(), and Pool::TableState::getEnd().
istream& Pool::operator>> (istream & is, NoiseType nt) inline
Definition at line 21 of file Noise.h.
Referenced by Pool::EightBallState::EightBallState(), Pool::EightBallState::importFromStream(), Pool::NineBallState::importFromStream(), Pool::NineBallState::NineBallState(), Pool::GameState::RackedState(), and Pool::GameState::shotRequired().
istream& Pool::operator>> (istream & is, TurnType & tt) inline
Definition at line 50 of file Rules.h.
void Pool::printEvents (list< Event * > events)
Dump event list to standard error.
Debugging function.
Definition at line 2704 of file FastFiz.cpp.
Referenced by getPoolfizVersion().
void Pool::printOverlap (TableState & ts)
Print overlapping balls in table state.
Debugging function.
Definition at line 2710 of file FastFiz.cpp.
References Pool::TableState::getBegin(), and Pool::TableState::getEnd().
Referenced by Pool::TableState::fixOverlap(), Pool::Shot::getDuration(), and getPoolfizVersion().
void Pool::rack (TableState & ts)
Rack table state for Eight-ball.
Debugging function.
Deprecated:
Use the GameState framework to generate a racked state.
Definition at line 2631 of file FastFiz.cpp.
Referenced by Pool::EightBallState::EightBallState(), getPoolfizVersion(), getTestState(), Pool::EightBallState::isLegalTurnType(), Pool::NineBallState::isLegalTurnType(), Pool::NineBallState::NineBallState(), and Pool::EightBallState::preProcess().